### ISSUE TITLE
Unable to connect to SFTP

### ISSUE THREAD

**Issue by isaumya** [Natizyskunk/vscode-sftp#10]
I have the following config in my `sftp.json` inside the `.vscode` folder:

```
{
  "protocol": "sftp",
  "host": "host.com",
  "port": 2222,
  "username": "username",
  "password": "pass"
}
```

But when I try to connect the connection is always getting timed out. On the other hand when I use the exact same details in FileZilla it works perfectly. In FileZilla after I connect, I get a popup like this which I need to accept in order to connect:

![Filezilla screenshot](https://i.imgur.com/bpKw9nZ.png)

But there is no such thing in the vs code extension. Also previously when I used the liximomo version of the extension, I never had this issue. After I uninstalled that extension and installed this one, I can see this issue.

I have also enabled the SFTP log to see what's going on and I see this in the log:

```
[07-08 14:08:37] [debug] Custom crypto binding not available
[07-08 14:08:37] [debug] Client: Trying ftp.sescollege.org on port 2222 ...
[07-08 14:08:37] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
[07-08 14:08:38] [debug] Socket connected
[07-08 14:08:38] [debug] Remote ident: 'SSH-2.0-OpenSSH_5.3'
[07-08 14:08:38] [debug] Outbound: Sending KEXINIT
[07-08 14:08:38] [debug] Inbound: Handshake in progress
[07-08 14:08:38] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[07-08 14:08:38] [debug] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[07-08 14:08:38] [debug] Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
[07-08 14:08:38] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[07-08 14:08:38] [debug] Handshake: (remote) Host key format: ssh-rsa,ssh-dss
[07-08 14:08:38] [debug] Handshake: Host key format: ssh-rsa
[07-08 14:08:38] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-08 14:08:38] [debug] Handshake: (remote) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[07-08 14:08:38] [debug] Handshake: C->S Cipher: aes128-ctr
[07-08 14:08:38] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-08 14:08:38] [debug] Handshake: (remote) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[07-08 14:08:38] [debug] Handshake: S->C cipher: aes128-ctr
[07-08 14:08:38] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-08 14:08:38] [debug] Handshake: (remote) C->S MAC: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[07-08 14:08:38] [debug] Handshake: C->S MAC: hmac-sha2-256
[07-08 14:08:38] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-08 14:08:38] [debug] Handshake: (remote) S->C MAC: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[07-08 14:08:38] [debug] Handshake: S->C MAC: hmac-sha2-256
[07-08 14:08:38] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[07-08 14:08:38] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[07-08 14:08:38] [debug] Handshake: C->S compression: none
[07-08 14:08:38] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[07-08 14:08:38] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[07-08 14:08:38] [debug] Handshake: S->C compression: none
[07-08 14:08:38] [debug] Outbound: Sending KEXDH_GEX_REQUEST
[07-08 14:08:38] [debug] Received DH GEX Group
[07-08 14:09:07] [debug] Outbound: Sending KEXDH_GEX_INIT
[07-08 14:09:07] [debug] Outbound: Sending DISCONNECT (11)
[07-08 14:09:07] [debug] Socket closed
```

Do you have any clue on how to resolve this matter so that I can use the extension?

**Comment by Natizyskunk** [comment]
Do you have defined all the needed parameters ?

Please try this config : 
```json
{
    "name": "<connection_name>",
    "host": "<hostname_or_ip>",
    "protocol": "sftp",
    "port": 22,
    "username": "<username>",
    "password": "<password>",
    "remotePath": "/<remote_path>"
}
```

Have you tried to connect via an SSH key ?
1. Create an SSH key on your local PC.
2. Add your local PC SSH public key inside your server "authorized_key" file. Don't forget to change permissions and ownership on your server : `chmod 600 ~/.ssh/authorized_keys` & `chown -R <username>:<username> ~/.ssh`.
3. On your local PC create inside your .ssh folder a "config" file and add this inside it :
```
PubkeyAcceptedKeyTypes=+ssh-dss

Host <server_name>
	HostName <server_host/server_ip>
	User <ssh_user>
	Port <ssh_port>
	IdentityFile <ssh_private_key_filepath>
```
4. On windows in your SFTP.json config file all slashes contained in the private key path should be replaced with double anti-slashes (this: `"privateKeyPath": "C:/Users/<Username>/.ssh/<private_key_file>"` become this: `"privateKeyPath": "C:\\Users\\<Username>\\.ssh\\<private_key_file>"`).
```json
{
    "username": "<username>",
    "privateKeyPath": "C:\\Users\\Natizyskunk\\.ssh\\id_rsa", // Replace "password" with "privateKeyPath".
}
```
5. Retry to connect and upload with azn SSH private key, it should work now.

**Comment by isaumya** [comment]
Hey @Natizyskunk,
> Do you have defined all the needed parameters ?

Yes I have. I have been using the original extension created by liximomo for many years and I am not new to this.  All parameters are added properly and in fact this same c onfig was working till yesterday when I was using the patched version of liximomo plugin without a single issue. It's only when I uninstalled that extension and installed yours the connection started failing while working perfectly on Filezilla and other FTP clients. Here is a screenshot of my actual config:

![my config](https://i.imgur.com/26scnfM.png)

> Have you tried to connect via an SSH key ?

No I haven't and I don't want to as the system should just work with username & password combination like it used to work and in fact still working with the original liximomo extension.

**Comment by Natizyskunk** [comment]
It's strange since I haven't change anything regarding the connection process. I've only bumped the ssh2 package to the v1.1.0 and added a switch to verify local files are saved before uploading them. I don't get why it work with liximomo's version but not mine.

Could you try this :
1. Uninstall extension from vscode.
2. Close vscode and go to `C:/Users/<username>/.vscode/extensions`. 
3. In here remove all references to the SFTP extension. Liximomo's one and Natizyskunk's one.
4. Re-open vscode and install latest version from the marketplace.
5.
PS : there seems to be an error the v1.13.3 version so I recommend you to use the v1.13.2 from [here](https://github.com/Natizyskunk/vscode-sftp/releases/tag/v1.13.2) and do the manual installation. I'll fix it when I'm back home later today.

**Comment by AlexMarcoDAngelo** [comment]
Why are we talking about an SSH key at all?? I have never had to deal with such thing before and I don’t want to start – it’s FTP protocol after all. If it works great with FileZilla, shouldn’t it work with this extension ?!

**Comment by isaumya** [comment]
Hey @Natizyskunk,
I did exactly as you asked (deleted all instances of the extension) and just now fresh installed the latest version of your extension i.e. v1.13.5 but unfortunately, the problem persists over SFTP and working fine on normal FTP.

I've also seen that this problem is happening with a few servers only. Not all servers. Yet the same SFTP details are working fine on Filezilla and WinScp.

**Comment by Natizyskunk** [comment]
For me the only thing i can think of right now is that this bug has been introduce with the update of the ssh2 package version to v1.1.0. I think so cause you say it was working fine with liximomo's one that uses v0.8.5 and between his version and mine the only changes are thoses :
```
* Update ssh2 npm package to 1.1.0 to : fix for the "No such file" error on VSCode 1.56 since it's been implementend in this new version + fix Writing CHANNEL_DATA (0) / Writing FSETSTAT.
* Add loggers for transfer informations.
* Fix issue with uploading of file which has unsaved changes.
* Fix transfer-test for Windows platform.
```
As you can see, there is nothing that I've changed that's messing up with the connection protocols or anything similar.

Are you maybe using some sort of firewall like `Little Snitch` that is used to block outgoing traffic or something like that ?

**Comment by isaumya** [comment]
Hi @Natizyskunk,
What you are saying is totally possible, but I don't know how to resolve that. Do you have any idea?

> Are you maybe using some sort of firewall like Little Snitch that is used to block outgoing traffic or something like that ?

No I am not. As I said the SFTP details are working file on FileZilla and WinSCP but not working via the extension. But FTP is working. 

But when I used the liximomo's version with manually editing the JS code to ensure that the "no such file" issue is fixed, there was no issue then.

Also as I said, it's not happing with all SFTP requests. Some SFTP is working fine but on some servers this issue is happeing.

**Comment by Natizyskunk** [comment]
@isaumya,
> But when I used the liximomo's version with manually editing the JS code to ensure that the "no such file" issue is fixed, there was no issue then.

This could confirm that the error has been introduce with the ssh2 package update to v1.1.0.

As a test to verify that you can try this : 
1. Uninstall SFTP extension from vscode.
2. Close vscode and go to `C:/Users/<username>/.vscode/extensions`. 
3. In here remove all references to the SFTP extension. Liximomo's one and Natizyskunk's one.
4. Re-open vscode and install latest liximomo's version, not mine.
5. Re-close vscode and navigate now to `C:/Users/<username>/.vscode/extensions/liximomo.sftp-1.12.9`.
6. In here edit the package.json file to update the ssh2 package version from 0.8.5 to 1.1.0 like this
![image](https://user-images.githubusercontent.com/59120131/125477738-c2400bf0-176b-42a7-87ec-7b48c9648f73.png)
!! Don't forget to save !!
7. Now open a terrminal inside the extension folder `C:/Users/<username>/.vscode/extensions/liximomo.sftp-1.12.9` and type npm i to update all the packages.
9. After that you can open vscode again and try to connect via the SFTP extension.
10. Now check if you still have the error or not. This will confirm if the bug is coming from the new ssh2 update.

Please give me your feedback.

**Comment by isaumya** [comment]
Hey @Natizyskunk,
First of all, after I installed the liximomo's version of extension that is coming with ssh2 v0.8.5, I can confirm that the SFTP is working perfectly on the server that was giving the issue.

![ss20.8.5](https://i.imgur.com/IYbjN4Y.png)

Now when I updated `ssh2` to v1.1.0 as you suggested above, I can confirm that I'm getting the exact same issue that I am getting with your extension. So, this confirms that the problem is coming from ssh2 v1.1.0

**Comment by Natizyskunk** [comment]
Nice, now we are moving forward.
I'm gonna open an issue on @mscdex ssh2 github to see if he can help me to fix this issue.
For now the only advise i can give you is to stay with liximomo's v0.8.5 and add this fix not get the "No such file or directory" error : [Fix streams autoDestroy, Node 14 major change #1009](https://github.com/mscdex/ssh2/pull/1009/files)

**Comment by Mickeywaugh** [comment]
I run into this issue too in 1.15.1,and sftp connection normal when I switch back to 1.14.0.
I usually do my development work on VMs, and these VMs always reinstall with same username and password as configed in sftp.json.
So when the VM reinstall, the Finger Prints is different, but the sftp extensions no reaction for this situation.
@Natizyskunk  May be, you can find a convinuent fork of  SSH2 on https://www.npmjs.com/ to solove this problem.

**Comment by Mickeywaugh** [comment]
useTempFile , this is not good idea.
I reviewed your commits from 1.14 to 1.15.1, this issue maybe cause by the codes for useTempFile.
I found serval files with .new file extension on my remote path.
It can not be unlinked and renamed successfully at remote side.

**Comment by Natizyskunk** [comment]
Could you try new release and tell me if the bug has been fixed please ?

**Comment by jjnxpct** [comment]
The new release is not on marketplace.visualstudio.com yet? How can we install this new release?

**Comment by Natizyskunk** [comment]
Give it some times since it's actually uploading on the Markeplace.
It should be available in 5 to 10 mins.

**Comment by Mickeywaugh** [comment]
> Could you try new release and tell me if the bug has been fixed please ?

Issue 1.15.2, this bug not fixed yet.

**Comment by Natizyskunk** [comment]
@Mickeywaugh,

Can you try this please ?

FAQ : https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#error-connection-closed

The problem would be that the SFTP extension keeps closing the connection for those who use more legacy/old systems. You'll have to Explicitly override the default transport layer algorithms used for the connection to remove the new "diffie-hellman-group-exchange-sha256" algorithm that cause the problem from the kex section. Just add this in your sftp.json config file, which should make it work.
```json
{
	...
	"host": "exemple.com",
	...
	"algorithms": {
		"kex": [
			"ecdh-sha2-nistp256", 
			"ecdh-sha2-nistp384", 
			"ecdh-sha2-nistp521", 
			"diffie-hellman-group14-sha1"
		],
		"cipher": [
			"aes128-ctr", 
			"aes192-ctr", 
			"aes256-ctr", 
			"aes128-gcm", 
			"aes128-gcm@openssh.com", 
			"aes256-gcm", 
			"aes256-gcm@openssh.com"
		],
		"serverHostKey": [
			"ssh-rsa", 
			"ecdsa-sha2-nistp256", 
			"ecdsa-sha2-nistp384", 
			"ecdsa-sha2-nistp521"
		],
		"hmac": [
			"hmac-sha2-256", 
			"hmac-sha2-512", 
			"hmac-sha1"
		]
	}
}
```


**References:** 
_Originally posted by @montorodiaz in https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-783402096_
https://github.com/liximomo/vscode-sftp/wiki/SFTP-only-Config#sshcustomparams

**Comment by Mickeywaugh** [comment]
@Natizyskunk  as your advise above, the  algorithms configuration seems  works with issue 1.15.2, good job!
TKS!

**Comment by Natizyskunk** [comment]
No problem, i'm happy to see that you've everything sorted out ! 😁
