### ISSUE TITLE
What is the sync limitation?

### ISSUE THREAD

**Issue by arafatx** [Natizyskunk/vscode-sftp#101]
Is there a documentation that show limitation of FTP download or sync from a folder? Some folders are not able to be downloaded (might be it has many subfolders). Folder with simple structure and files are able to be synced from remote to local but for big file or many folder structures, the ftp icon just spinning without telling any clues what is going on.

**Comment by Natizyskunk** [comment]
As said in (this](https://www.tutsandtips.com/ftp/what-is-the-maximum-file-size-in-ftp-transfers/) article "By default, there is no technical limit on the maximum file size that you can transfer (download/upload) via FTP".
