### ISSUE TITLE
大佬，考虑支持下 FTP Over TLS吗？

### ISSUE THREAD

**Issue by laterz** [Natizyskunk/vscode-sftp#102]
服务器pure-ftp开启了，仅限TLS的连接

连接时返回
Sorry, cleartext sessions and weak ciphers are not accepted on this server.
Please reconnect using TLS security mechanisms.

**Comment by Natizyskunk** [comment]
@laterz, 

Please comment in English.

Now concerning your bug, It seems that you're trying to connect to a not secured server.
Can you tell me what FTP/SSH server (ex: OpenSSH) you're using and which version please ?
