### ISSUE TITLE
能否在我的代码里读取sftp的配置吗，例如profile

### ISSUE THREAD

**Issue by TuKun33** [Natizyskunk/vscode-sftp#104]
**Is this a similar or duplicate feature request?**
- [x] I don't know. I will go check it.
- [ ] No.

**Is your feature request related to a problem? Please describe.**

我想在我的代码里读取当前的profile, 我可以读取.vscode/sftp.json，但那是静态的

**Describe the solution you'd like**

设置profile的时候，可以考虑在.vscode/sftp.json 写入 currentProfile 属性，或者写入process对象（我是nodejs项目）

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@TuKun33,

Please write in english so everyone can understand including me ^^

Thx in advance 🙂
