### ISSUE TITLE
Sync deleted file on remote

### ISSUE THREAD

**Issue by dolutattoo** [Natizyskunk/vscode-sftp#107]
**Do you read the FAQ?**
- Yes.

**Describe the bug**
I set `watcher.autoDelete` and `watcher.autoUpload` to true, but if I delete a file locally in vscode, the file still exist on remote.

**To Reproduce**
1. set  `watcher.autoDelete` and `watcher.autoUpload` to true
2. delete a file by doing RMB>Delete file
3. File still exists on remote

**Expected behavior**
Once I delete a file locally, extension should ask if I also want to delete it on remote

**Desktop (please complete the following information):**
 - OS: Win 11
 - VSCode Version 1.63.2
 - Extension Version 1.15.10

**Comment by fjqingyou** [comment]
Moving files has the same problem

**Comment by Natizyskunk** [comment]
You should be able to achieve what you want with this config :

```json
{
    "...",
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "...",
    "syncOption":{
        "delete": true
    },
    "...",
}
    "uploadOnSave": false, // set to false if watcher `autoUpload` is set to true & `files` is set to "**/*".
```

Can you try it and tell me if it fixed your problem ?

**Comment by fjqingyou** [comment]
> 
it's right. rename and delete file is sync to remote server
thanks! have a good day!
