### ISSUE TITLE
Upload changed files not working - sync data not working

### ISSUE THREAD

**Issue by 7amoood** [Natizyskunk/vscode-sftp#108]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When using the command upload changed files -> it says upload and write the file name but nothing uploaded.
when using sync data local -> remote it does not upload any data however I changed the file content

**Comment by Natizyskunk** [comment]
@7amoood,
It seems to be a bug on your end. 

Can you try this please : 
1. Delete SFTP extension from vscode (liximomo's version and mine).
2. Close and exit vscode.
3. Navigate to C:\Users\<username>\.vscode\extensions and remove all occurences of SFTP Extension (liximomo's version and mine).
4. Open vscode again & go to the extensions tab (CTRL + SHIFT + X) and install the last version of my SFTP extension.

**Comment by 7amoood** [comment]
Solved thanks

**Comment by Natizyskunk** [comment]
@7amoood,

No problem. I Happy to know that everything work fine.

**Comment by jano23** [comment]
I'm having the same issue. Windows 11
Tried the suggested fix of uninstalling all versions, deleting all occurrences of the extension, restarting vscode and reinstalling."
Output on Terminal shows UPLOAD: results correctly on the 3 files I am testing but the server still has the old versions.
SFTP v1.15.14
VSCODE v1.70.0
