### ISSUE TITLE
希望多重上下文批量同步支持

### ISSUE THREAD

**Issue by fjqingyou** [Natizyskunk/vscode-sftp#125]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
抱歉，我英语不好，所以用母语进行提交反馈！

对于多重上下文环境下有非常多的影射配置的情况下。

本地项目并不全部影射到远程，例如有些在根目录的文件夹是本地开发环境用的文件夹。

当前需要同步时，总是需要展开到上下文环境的文件夹，然后右键选择文件夹进行同步。当上下文环境很多个的时候，这个过程有些机械化，重复性操作很多，不同点只是多重上下文配置对应的文件夹路径的不同。

**Describe the solution you'd like**
期望在根目录下进行同步时，不是因为根目录没有影射就弹出 [error] Error: Config Not Found 而是提示选择同步全部，或者更精细的提示选择某个或多个配置的上下文进行批量同步。

**Describe alternatives you've considered**
替代方案当前能想到的唯有逐个文件夹手动同步这个方式了

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
Related issues : #127, #156, #187

**Comment by fjqingyou** [comment]
与列出来的几个issus稍微有点不同，等下班之后，我梳理下流程，做一下详细的工作环境和操作步骤反馈！

**Comment by Natizyskunk** [comment]
@fjqingyou pleasr right in English so everyone can understand.

**Comment by Natizyskunk** [comment]
Should be fixed in new v1.16.2 release.
