### ISSUE TITLE
Refer to external file when configuring sftp.json

### ISSUE THREAD

**Issue by hdd1013** [Natizyskunk/vscode-sftp#126]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
current sftp config file requires passwords to be included in a file, which becomes a problem if you want to include the sftp.json file in the version control

**Describe the solution you'd like**
introduce a feature that lets users to refer to a separate secret file that can be safely excluded from the version control. possible suggestions: 

1. refer to an external file using syntax like VS Code variables.

```
## sftp.json ##
{
    "name": "MyRemote",
    "host": "myremote.com",
    "protocol": "sftp",
    "port": 22,
    "username": "remoteuser",
    "remotePath": "/remote-app",
    "externalConfig": ${workspaceFolder:myapp}/.vscode/sftp-secret.json
}

## sftp-secret.json ##
{
    "password": "myReMoTeP@ssword!"
}
```

2. use override file
```
## sftp.json ##
{
    "name": "MyRemote",
    "host": "myremote.com",
    "protocol": "sftp",
    "port": 22,
    "username": "remoteuser",
    "remotePath": "/remote-app"
}

## sftp.override.json ##
{
    "password": "myReMoTeP@ssword!"
}
```

**Describe alternatives you've considered**

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
The easiest way of doing it is to create a generic sftp.json.dist file that you'll versionned. In it you can add everything you need except the password. Then add a .gitignore with sftp.json file in it. Then when a user clone the project he just have to copy the sftp.json.dist to sftp.json and add the password in it. This file will never be versionned.
This should fix your problem.
