### ISSUE TITLE
Exclude files, folders, or file types

### ISSUE THREAD

**Issue by mpariente** [Natizyskunk/vscode-sftp#128]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [X] No.

**Is your feature request related to a problem? Please describe.**
I'd love to sync only some file types and keep others unsynced. 

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME! :upside_down_face:

**Comment by Natizyskunk** [comment]
@mpariente, Can you be more precise please ? 🙂

**Comment by mpariente** [comment]
When using either `Sync Local->Remote` or `Sync Remote->Local` on a folder, all its files and subfolders will be synced. This is the expected behavior. 

But, if there is one subfolder, or one file that I wouldn't want to sync between Remote and Local, there is no easy way to do it right ? Same for file types (e.g. *.wav files which I don't want to download and upload back and forth).

This feature request is to add this possibility. Does it seem feasible?

**Comment by Natizyskunk** [comment]
@mpariente, ok I see.
You can easily achieve this by using the ignore parameter in your `sftp.json` config file. You can see more details [here](https://github.com/Natizyskunk/vscode-sftp/wiki/Common-Config#ignore).
