### ISSUE TITLE
Gae it another try and still nothing :(

### ISSUE THREAD

**Issue by AlexMarcoDAngelo** [Natizyskunk/vscode-sftp#13]
Back in the day loved the original SFTP, so now when I saw it is resurrected, I tried to use it again. Sadly, the error it gives me doesn't mean anything to me, so any help from anyone would be appreciated! 
The debug shows only this:
    [07-08 22:21:45] [debug] > AUTH TLS
    [07-08 22:21:45] [debug] < '234 AUTH TLS OK.\r\n'
After which a pop-up message shows this:
    "Hostname/IP does not match certificate's altnames: IP: 68.65.121.171 is not in the cert's list: "

**Comment by Natizyskunk** [comment]
Can you give me more details ?

Please reffer to the [issue template](https://github.com/Natizyskunk/vscode-sftp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) please.

**Comment by AlexMarcoDAngelo** [comment]
Do you read the FAQ?
 **Yes.**

Describe the bug A clear and concise description of what the bug is.
  **Does not connect to the remote server**
To Reproduce Steps to reproduce the behavior:
  **Try to connect**
Go to '...'
Run command '....'
See error:
  **"Hostname/IP does not match certificate's altnames: IP: 68.65.121.171 is not in the cert's list: "**
Expected behavior A clear and concise description of what you expected to happen.
  **To connect to the remote server and list the files there**
Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Mac, Win, Linux]  **Windows 10**
VSCode Version [e.g. 1.51.0]  **1.58.0. User**
Extension Version [e.g. 1.7.0]  **v1.13.3** 
Extension Logs from Startup - required 
Reproduce the problem, get the logs from View > Output > sftp.
  **[07-08 22:21:45] [debug] > AUTH TLS
  [07-08 22:21:45] [debug] < '234 AUTH TLS OK.\r\n'**

What is that error message about cert list?! I never had to deal with certificates before... And the debug stops right there.

**Comment by AlexMarcoDAngelo** [comment]
Trying now with a KEY (which I never had to do before btw).. SFTP extension keeps closing the connection:

[07-12 09:53:03] [info] config at d:\OneDrive\Websites\leonardomedicine_com {"remotePath":"/home/tarahost/leonardomedicine","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store",".well-known",".rar"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":true,"remoteTimeOffsetInHours":0,"name":"TARAHOSTING","host":"68.65.121.171","port":21098,"privateKeyPath":"D:/OneDrive/id_rsa.ppk","passphrase":"******","username":"******","password":"******"}
[07-12 09:53:03] [debug] Custom crypto binding not available
[07-12 09:53:03] [debug] Client: Trying 68.65.121.171 on port 21098 ...
[07-12 09:53:03] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
[07-12 09:53:03] [debug] Socket connected
[07-12 09:53:03] [debug] Remote ident: 'SSH-2.0-OpenSSH_5.3'
[07-12 09:53:03] [debug] Outbound: Sending KEXINIT
[07-12 09:53:04] [debug] Inbound: Handshake in progress
[07-12 09:53:04] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[07-12 09:53:04] [debug] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[07-12 09:53:04] [debug] Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
[07-12 09:53:04] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[07-12 09:53:04] [debug] Handshake: (remote) Host key format: ssh-rsa,ssh-dss
[07-12 09:53:04] [debug] Handshake: Host key format: ssh-rsa
[07-12 09:53:04] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-12 09:53:04] [debug] Handshake: (remote) C->S cipher: aes256-ctr,aes192-ctr,aes128-ctr
[07-12 09:53:04] [debug] Handshake: C->S Cipher: aes128-ctr
[07-12 09:53:04] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-12 09:53:04] [debug] Handshake: (remote) S->C cipher: aes256-ctr,aes192-ctr,aes128-ctr
[07-12 09:53:04] [debug] Handshake: S->C cipher: aes128-ctr
[07-12 09:53:04] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-12 09:53:04] [debug] Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-ripemd160@openssh.com
[07-12 09:53:04] [debug] Handshake: C->S MAC: hmac-sha2-256
[07-12 09:53:04] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-12 09:53:04] [debug] Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-ripemd160@openssh.com
[07-12 09:53:04] [debug] Handshake: S->C MAC: hmac-sha2-256
[07-12 09:53:04] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[07-12 09:53:04] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[07-12 09:53:04] [debug] Handshake: C->S compression: none
[07-12 09:53:04] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[07-12 09:53:04] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[07-12 09:53:04] [debug] Handshake: S->C compression: none
[07-12 09:53:04] [debug] Outbound: Sending KEXDH_GEX_REQUEST
[07-12 09:53:04] [debug] Received DH GEX Group
[07-12 09:53:22] [debug] Outbound: Sending KEXDH_GEX_INIT
[07-12 09:53:22] [debug] Outbound: Sending DISCONNECT (11)
[07-12 09:53:22] [debug] Socket closed

**Comment by Natizyskunk** [comment]
Have you correctly configured your sftp.json config file ?

Also could you try this and see if you still have the error :
1. Uninstall extension from vscode.
2. Close vscode and go to `C:/Users/<username>/.vscode/extensions`. 
3. In here remove all references to the SFTP extension. Liximomo's one and Natizyskunk's one.
4. Re-open vscode and install latest version from the marketplace.

Please give me some feedbacks 🙂

**Comment by KFRANCMM** [comment]
> Trying now with a KEY (which I never had to do before btw).. SFTP extension keeps closing the connection:
> 
> [07-12 09:53:03] [info] config at d:\OneDrive\Websites\leonardomedicine_com {"remotePath":"/home/tarahost/leonardomedicine","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store",".well-known",".rar"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":true,"remoteTimeOffsetInHours":0,"name":"TARAHOSTING","host":"68.65.121.171","port":21098,"privateKeyPath":"D:/OneDrive/id_rsa.ppk","passphrase":"******","username":"******","password":"******"}
> [07-12 09:53:03] [debug] Custom crypto binding not available
> [07-12 09:53:03] [debug] Client: Trying 68.65.121.171 on port 21098 ...
> [07-12 09:53:03] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
> [07-12 09:53:03] [debug] Socket connected
> [07-12 09:53:03] [debug] Remote ident: 'SSH-2.0-OpenSSH_5.3'
> [07-12 09:53:03] [debug] Outbound: Sending KEXINIT
> [07-12 09:53:04] [debug] Inbound: Handshake in progress
> [07-12 09:53:04] [debug] Handshake: (local) KEX method: [curve25519-sha256@libssh.org](mailto:curve25519-sha256@libssh.org),curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
> [07-12 09:53:04] [debug] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
> [07-12 09:53:04] [debug] Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
> [07-12 09:53:04] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
> [07-12 09:53:04] [debug] Handshake: (remote) Host key format: ssh-rsa,ssh-dss
> [07-12 09:53:04] [debug] Handshake: Host key format: ssh-rsa
> [07-12 09:53:04] [debug] Handshake: (local) C->S cipher: aes128-gcm,[aes128-gcm@openssh.com](mailto:aes128-gcm@openssh.com),aes256-gcm,[aes256-gcm@openssh.com](mailto:aes256-gcm@openssh.com),aes128-ctr,aes192-ctr,aes256-ctr,[chacha20-poly1305@openssh.com](mailto:chacha20-poly1305@openssh.com)
> [07-12 09:53:04] [debug] Handshake: (remote) C->S cipher: aes256-ctr,aes192-ctr,aes128-ctr
> [07-12 09:53:04] [debug] Handshake: C->S Cipher: aes128-ctr
> [07-12 09:53:04] [debug] Handshake: (local) S->C cipher: aes128-gcm,[aes128-gcm@openssh.com](mailto:aes128-gcm@openssh.com),aes256-gcm,[aes256-gcm@openssh.com](mailto:aes256-gcm@openssh.com),aes128-ctr,aes192-ctr,aes256-ctr,[chacha20-poly1305@openssh.com](mailto:chacha20-poly1305@openssh.com)
> [07-12 09:53:04] [debug] Handshake: (remote) S->C cipher: aes256-ctr,aes192-ctr,aes128-ctr
> [07-12 09:53:04] [debug] Handshake: S->C cipher: aes128-ctr
> [07-12 09:53:04] [debug] Handshake: (local) C->S MAC: [hmac-sha2-256-etm@openssh.com](mailto:hmac-sha2-256-etm@openssh.com),[hmac-sha2-512-etm@openssh.com](mailto:hmac-sha2-512-etm@openssh.com),[hmac-sha1-etm@openssh.com](mailto:hmac-sha1-etm@openssh.com),hmac-sha2-256,hmac-sha2-512,hmac-sha1
> [07-12 09:53:04] [debug] Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,[hmac-ripemd160@openssh.com](mailto:hmac-ripemd160@openssh.com)
> [07-12 09:53:04] [debug] Handshake: C->S MAC: hmac-sha2-256
> [07-12 09:53:04] [debug] Handshake: (local) S->C MAC: [hmac-sha2-256-etm@openssh.com](mailto:hmac-sha2-256-etm@openssh.com),[hmac-sha2-512-etm@openssh.com](mailto:hmac-sha2-512-etm@openssh.com),[hmac-sha1-etm@openssh.com](mailto:hmac-sha1-etm@openssh.com),hmac-sha2-256,hmac-sha2-512,hmac-sha1
> [07-12 09:53:04] [debug] Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,[hmac-ripemd160@openssh.com](mailto:hmac-ripemd160@openssh.com)
> [07-12 09:53:04] [debug] Handshake: S->C MAC: hmac-sha2-256
> [07-12 09:53:04] [debug] Handshake: (local) C->S compression: none,[zlib@openssh.com](mailto:zlib@openssh.com),zlib
> [07-12 09:53:04] [debug] Handshake: (remote) C->S compression: none,[zlib@openssh.com](mailto:zlib@openssh.com)
> [07-12 09:53:04] [debug] Handshake: C->S compression: none
> [07-12 09:53:04] [debug] Handshake: (local) S->C compression: none,[zlib@openssh.com](mailto:zlib@openssh.com),zlib
> [07-12 09:53:04] [debug] Handshake: (remote) S->C compression: none,[zlib@openssh.com](mailto:zlib@openssh.com)
> [07-12 09:53:04] [debug] Handshake: S->C compression: none
> [07-12 09:53:04] [debug] Outbound: Sending KEXDH_GEX_REQUEST
> [07-12 09:53:04] [debug] Received DH GEX Group
> [07-12 09:53:22] [debug] Outbound: Sending KEXDH_GEX_INIT
> [07-12 09:53:22] [debug] Outbound: Sending DISCONNECT (11)
> [07-12 09:53:22] [debug] Socket closed

Hello, from the debug messages you seem to have the same problem that happened to me.

The extension works fine with other SFTP servers, but one in particular is old and apparently the SSH version has not been updated. I don't know what version the server has, because I don't have access to the settings. 

Looking for what was the problem, I tried to modify the allowed algorithms, except `diffie-hellman-group-exchange-sha256` in the configuration and it worked!

Here is my config:
``` "name": "SFTP-SERVER",
    "host": "**********",
    "protocol": "sftp",
    "port": 22,
    "username": "*********",
    "password": "*********",
    "remotePath": "/var/www/html/",
    "uploadOnSave": true,
    "algorithms": {
        "kex": [
            "ecdh-sha2-nistp256",
            "ecdh-sha2-nistp384",
            "ecdh-sha2-nistp521",
            "diffie-hellman-group14-sha1"
        ],
        "cipher": [
            "aes128-ctr",
            "aes192-ctr",
            "aes256-ctr",
            "aes128-gcm",
            "aes128-gcm@openssh.com",
            "aes256-gcm",
            "aes256-gcm@openssh.com"
        ],
        "serverHostKey": [
            "ssh-rsa",
            "ecdsa-sha2-nistp256",
            "ecdsa-sha2-nistp384",
            "ecdsa-sha2-nistp521"
        ],
        "hmac": [
            "hmac-sha2-256",
            "hmac-sha2-512",
            "hmac-sha1"
        ]
    } 
```

**References:** 
_Originally posted by @montorodiaz in https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-783402096_
https://github.com/liximomo/vscode-sftp/wiki/SFTP-only-Config#sshcustomparams

@Natizyskunk  thanks for reviving this pluggin :)
Working in 
```
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by Natizyskunk** [comment]
> > Trying now with a KEY (which I never had to do before btw).. SFTP extension keeps closing the connection:
> > [07-12 09:53:03] [info] config at d:\OneDrive\Websites\leonardomedicine_com {"remotePath":"/home/tarahost/leonardomedicine","uploadOnSave":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store",".well-known",".rar"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":true,"remoteTimeOffsetInHours":0,"name":"TARAHOSTING","host":"68.65.121.171","port":21098,"privateKeyPath":"D:/OneDrive/id_rsa.ppk","passphrase":"******","username":"******","password":"******"}
> > [07-12 09:53:03] [debug] Custom crypto binding not available
> > [07-12 09:53:03] [debug] Client: Trying 68.65.121.171 on port 21098 ...
> > [07-12 09:53:03] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
> > [07-12 09:53:03] [debug] Socket connected
> > [07-12 09:53:03] [debug] Remote ident: 'SSH-2.0-OpenSSH_5.3'
> > [07-12 09:53:03] [debug] Outbound: Sending KEXINIT
> > [07-12 09:53:04] [debug] Inbound: Handshake in progress
> > [07-12 09:53:04] [debug] Handshake: (local) KEX method: [curve25519-sha256@libssh.org](mailto:curve25519-sha256@libssh.org),curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
> > [07-12 09:53:04] [debug] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
> > [07-12 09:53:04] [debug] Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
> > [07-12 09:53:04] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
> > [07-12 09:53:04] [debug] Handshake: (remote) Host key format: ssh-rsa,ssh-dss
> > [07-12 09:53:04] [debug] Handshake: Host key format: ssh-rsa
> > [07-12 09:53:04] [debug] Handshake: (local) C->S cipher: aes128-gcm,[aes128-gcm@openssh.com](mailto:aes128-gcm@openssh.com),aes256-gcm,[aes256-gcm@openssh.com](mailto:aes256-gcm@openssh.com),aes128-ctr,aes192-ctr,aes256-ctr,[chacha20-poly1305@openssh.com](mailto:chacha20-poly1305@openssh.com)
> > [07-12 09:53:04] [debug] Handshake: (remote) C->S cipher: aes256-ctr,aes192-ctr,aes128-ctr
> > [07-12 09:53:04] [debug] Handshake: C->S Cipher: aes128-ctr
> > [07-12 09:53:04] [debug] Handshake: (local) S->C cipher: aes128-gcm,[aes128-gcm@openssh.com](mailto:aes128-gcm@openssh.com),aes256-gcm,[aes256-gcm@openssh.com](mailto:aes256-gcm@openssh.com),aes128-ctr,aes192-ctr,aes256-ctr,[chacha20-poly1305@openssh.com](mailto:chacha20-poly1305@openssh.com)
> > [07-12 09:53:04] [debug] Handshake: (remote) S->C cipher: aes256-ctr,aes192-ctr,aes128-ctr
> > [07-12 09:53:04] [debug] Handshake: S->C cipher: aes128-ctr
> > [07-12 09:53:04] [debug] Handshake: (local) C->S MAC: [hmac-sha2-256-etm@openssh.com](mailto:hmac-sha2-256-etm@openssh.com),[hmac-sha2-512-etm@openssh.com](mailto:hmac-sha2-512-etm@openssh.com),[hmac-sha1-etm@openssh.com](mailto:hmac-sha1-etm@openssh.com),hmac-sha2-256,hmac-sha2-512,hmac-sha1
> > [07-12 09:53:04] [debug] Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,[hmac-ripemd160@openssh.com](mailto:hmac-ripemd160@openssh.com)
> > [07-12 09:53:04] [debug] Handshake: C->S MAC: hmac-sha2-256
> > [07-12 09:53:04] [debug] Handshake: (local) S->C MAC: [hmac-sha2-256-etm@openssh.com](mailto:hmac-sha2-256-etm@openssh.com),[hmac-sha2-512-etm@openssh.com](mailto:hmac-sha2-512-etm@openssh.com),[hmac-sha1-etm@openssh.com](mailto:hmac-sha1-etm@openssh.com),hmac-sha2-256,hmac-sha2-512,hmac-sha1
> > [07-12 09:53:04] [debug] Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,[hmac-ripemd160@openssh.com](mailto:hmac-ripemd160@openssh.com)
> > [07-12 09:53:04] [debug] Handshake: S->C MAC: hmac-sha2-256
> > [07-12 09:53:04] [debug] Handshake: (local) C->S compression: none,[zlib@openssh.com](mailto:zlib@openssh.com),zlib
> > [07-12 09:53:04] [debug] Handshake: (remote) C->S compression: none,[zlib@openssh.com](mailto:zlib@openssh.com)
> > [07-12 09:53:04] [debug] Handshake: C->S compression: none
> > [07-12 09:53:04] [debug] Handshake: (local) S->C compression: none,[zlib@openssh.com](mailto:zlib@openssh.com),zlib
> > [07-12 09:53:04] [debug] Handshake: (remote) S->C compression: none,[zlib@openssh.com](mailto:zlib@openssh.com)
> > [07-12 09:53:04] [debug] Handshake: S->C compression: none
> > [07-12 09:53:04] [debug] Outbound: Sending KEXDH_GEX_REQUEST
> > [07-12 09:53:04] [debug] Received DH GEX Group
> > [07-12 09:53:22] [debug] Outbound: Sending KEXDH_GEX_INIT
> > [07-12 09:53:22] [debug] Outbound: Sending DISCONNECT (11)
> > [07-12 09:53:22] [debug] Socket closed
> 
> Hello, from the debug messages you seem to have the same problem that happened to me.
> 
> The extension works fine with other SFTP servers, but one in particular is old and apparently the SSH version has not been updated. I don't know what version the server has, because I don't have access to the settings.
> 
> Looking for what was the problem, I tried to modify the allowed algorithms, except `diffie-hellman-group-exchange-sha256` in the configuration and it worked!
> 
> Here is my config:
> 
> ```
>     "host": "**********",
>     "protocol": "sftp",
>     "port": 22,
>     "username": "*********",
>     "password": "*********",
>     "remotePath": "/var/www/html/",
>     "uploadOnSave": true,
>     "algorithms": {
>         "kex": [
>             "ecdh-sha2-nistp256",
>             "ecdh-sha2-nistp384",
>             "ecdh-sha2-nistp521",
>             "diffie-hellman-group14-sha1"
>         ],
>         "cipher": [
>             "aes128-ctr",
>             "aes192-ctr",
>             "aes256-ctr",
>             "aes128-gcm",
>             "aes128-gcm@openssh.com",
>             "aes256-gcm",
>             "aes256-gcm@openssh.com"
>         ],
>         "serverHostKey": [
>             "ssh-rsa",
>             "ecdsa-sha2-nistp256",
>             "ecdsa-sha2-nistp384",
>             "ecdsa-sha2-nistp521"
>         ],
>         "hmac": [
>             "hmac-sha2-256",
>             "hmac-sha2-512",
>             "hmac-sha1"
>         ]
>     } 
> ```
> 
> **References:**
> _Originally posted by @montorodiaz in [liximomo#883 (comment)](https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-783402096)_
> https://github.com/liximomo/vscode-sftp/wiki/SFTP-only-Config#sshcustomparams
> 
> @Natizyskunk thanks for reviving this pluggin :)
> Working in
> 
> ```
> Version: 1.59.0 (user setup)
> Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
> Date: 2021-08-04T23:13:12.822Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Windows_NT x64 10.0.18363
> ```

@AlexMarcoDAngelo,
Could you try @KFRANCMM method and see if it work ?

**Comment by Natizyskunk** [comment]
FAQ : https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#error-connection-closed

The problem would be that the SFTP extension keeps closing the connection for those who use more legacy/old systems. You'll have to Explicitly override the default transport layer algorithms used for the connection to remove the new "diffie-hellman-group-exchange-sha256" algorithm that cause the problem from the kex section. Just add this in your sftp.json config file, which should make it work.
```json
{
	...
	"host": "exemple.com",
	...
	"algorithms": {
		"kex": [
			"ecdh-sha2-nistp256", 
			"ecdh-sha2-nistp384", 
			"ecdh-sha2-nistp521", 
			"diffie-hellman-group14-sha1"
		],
		"cipher": [
			"aes128-ctr", 
			"aes192-ctr", 
			"aes256-ctr", 
			"aes128-gcm", 
			"aes128-gcm@openssh.com", 
			"aes256-gcm", 
			"aes256-gcm@openssh.com"
		],
		"serverHostKey": [
			"ssh-rsa", 
			"ecdsa-sha2-nistp256", 
			"ecdsa-sha2-nistp384", 
			"ecdsa-sha2-nistp521"
		],
		"hmac": [
			"hmac-sha2-256", 
			"hmac-sha2-512", 
			"hmac-sha1"
		]
	}
}
```


**References:** 
_Originally posted by @montorodiaz in https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-783402096_
https://github.com/liximomo/vscode-sftp/wiki/SFTP-only-Config#sshcustomparams
