### ISSUE TITLE
Reveal in Remote Explorer Issue

### ISSUE THREAD

**Issue by sgtcoder** [Natizyskunk/vscode-sftp#133]
**Do you read the FAQ?**
Yes

**Describe the bug**
View in Remote Explorer not working. It does work once you goto Remote Explorer, manually connect to server, then go back to local explorer, then right click and View in Remote Explorer.

**To Reproduce**
Right click a file in Explorer and click View in Remote Explorer

**Expected behavior**
It should switch to the Remote Explorer on the sidebar.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - VSCode Version: 1.65.2
 - Extension Version: 1.15.13

**Extension Logs from Startup** - *required*
No log was created.

Update: The Output later finally appeared: `[03-18 18:04:28] [trace] run command 'Reveal In Remote Explorer'`
But it doesn't open the sidebar.

**Comment by kadikey58** [comment]
Have the same problem - never worked for me!
