### ISSUE TITLE
Refresh Remote Explorer when Creating/Deleting Files/Folders

### ISSUE THREAD

**Issue by sgtcoder** [Natizyskunk/vscode-sftp#134]
**Is this a similar or duplicate feature request?**
I did not see any.

**Is your feature request related to a problem? Please describe.**
No, would like a new feature to trigger an auto-refresh.

**Describe the solution you'd like**
Ability for Remote Explorer to refresh the folder when a modification was made. For example: Deleting a file should auto refresh vs having to manually do it.

**Describe alternatives you've considered**
Have to create files on remote or delete them, Then have to refresh each time at the top.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
Related issues : #47, #122, #159
