### ISSUE TITLE
Automatically sync both ways without user interaction

### ISSUE THREAD

**Issue by MRVDH** [Natizyskunk/vscode-sftp#136]
**Is this a similar or duplicate feature request?**
No.

**Is your feature request related to a problem? Please describe.**
I was unable to find from the docs if there is a setting that makes sure that local is always up to date with remote. A setting that automatically synchronises everything near-instantly (like how CodeTasty does it, or Google Drive, Dropbox, etc). 

**Describe the solution you'd like**
A setting that syncs local with remote and the other way around automatically, without any user interaction. Similar to CodeTasty and Google Drive, Dropbox, etc

**Describe alternatives you've considered**
Unable to find. So far I use a combination of the `Sync Remote -> Local` command, and the `uploadOnSave` and `downloadOnOpen` options.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
You should be able to achieve what you want with this config :

```json
{
    "...",
    "watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "...",
    "syncOption":{
        "delete": true
    },
    "...",
}
    "uploadOnSave": false, // set to false if watcher `autoUpload` is set to true & `files` is set to "**/*".
```
