### ISSUE TITLE
There is no simple disconnect command?

### ISSUE THREAD

**Issue by WebSpectrum** [Natizyskunk/vscode-sftp#138]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I can't a simple disconnect from remote command?

**Describe alternatives you've considered**

**Does this project help you?**
- [ ] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
why would you want such a command ?
