### ISSUE TITLE
Getting "Error with the transfer direction. Direction seems not to be local to remote." on remote -> local

### ISSUE THREAD

**Issue by eymerich** [Natizyskunk/vscode-sftp#14]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Each file (local and remote both existing) or folder I try to donwload I got the same error:
**Error with the transfer direction. Direction seems not to be local to remote.**

Looking in the git blame for transfer.ts seems like you have put a switch from liximomo under a if
`if (config.transferDirection === TransferDirection.LOCAL_TO_REMOTE) {`
that actually it's hampering the function functionalities (screen attached below) for the others legit actions different from a local to remote.

**To Reproduce**
1. Create a folder in local project
2. Create same folder on the remote machine in the configured folder as your sftp config
3. Right click on local folder in VSCODE and select "Download"
- Same apply for files -

**Expected behavior**
Remote folder with all his contents (or selected file) is downloaded overwriting the local contents.

**Screenshots**
![s1](https://user-images.githubusercontent.com/762052/125058612-bc1cd380-e0aa-11eb-9dbe-be5f3f909df8.png)
![s2](https://user-images.githubusercontent.com/762052/125058722-d9ea3880-e0aa-11eb-8895-0e7172441d3b.png)
![s3](https://user-images.githubusercontent.com/762052/125058741-dd7dbf80-e0aa-11eb-98a8-9561ddca9405.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version: 1.58.0
 - Extension Version: 1.13.3

**Comment by Natizyskunk** [comment]
My bad that's an error from me, as a temporary solution you can download the previous release v1.13.2 [here](https://github.com/Natizyskunk/vscode-sftp/releases/tag/v1.13.2) and do the manual installation. I'll fix it when I'm back home later today.

**Comment by Natizyskunk** [comment]
Everything has been fixed now. You can download the latest version (v1.13.5) directly from marketplace or just restart your vscode.
