### ISSUE TITLE
sftp.json -> ignore problem

### ISSUE THREAD

**Issue by tjgh1322** [Natizyskunk/vscode-sftp#143]
**Do you read the FAQ?**
- [v] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
- I set the "ignore" like this
![image](https://user-images.githubusercontent.com/82634713/161512342-71b804f1-ddee-493c-a029-38bc3adf90da.png)

**To Reproduce**
And then execute SFTP : Remote To Local 
![image](https://user-images.githubusercontent.com/82634713/161512892-88c40bc1-5256-4f14-a8d2-aac597a7e3d3.png)

![image](https://user-images.githubusercontent.com/82634713/161513068-5298d567-c856-4ef1-891d-b2c71ec1ce39.png)
How can I solve it?

**Comment by NyaPPuu** [comment]
How about set to `/data/session` or `data/session`?
I don't know if this is correct,
Because you set remotePath, I think you should remove that remotePath value.

**Comment by tjgh1322** [comment]
> How about set to `/data/session` or `data/session`? I don't know if this is correct, Because you set remotePath, I think you should remove that remotePath value.

OHHHHHHHHHHHHHHHHHHHHH!
I solve it!!! thanks a lot!! :D
