### ISSUE TITLE
..... load C:\Users\username\.ssh\config failed

### ISSUE THREAD

**Issue by develop-cloud** [Natizyskunk/vscode-sftp#148]
I'm unable to sync, destination and local. Using Visual Studio Code on Windows.

[warn] ENOENT: no such file or directory, open 'C:\Users\username\.ssh\config' load C:\Users\username\.ssh\config failed

Is the message in the 'Output'. Explorer -> R.Mouse on .vscode - 'Sync Both Directions'
sftp.json is configured.

Please advice

**Comment by Natizyskunk** [comment]
@develop-cloud,
Please create a [bug report](https://github.com/Natizyskunk/vscode-sftp/issues/new?assignees=&labels=&template=bug_report.md&title=) respecting the template.

**Comment by gsabater** [comment]
@develop-cloud 
I had the same problem. 
Fixed it by just creating a folder inside my username folder called  `.ssh` and then a blank file called config in it
