### ISSUE TITLE
Support temp files creation when uploading (and then move over dest file to not break the site while uploading)

### ISSUE THREAD

**Issue by kripper** [Natizyskunk/vscode-sftp#16]
Hi Natizyskunk, thanks for reviving this critical plugin.

This is a simple and usefull feature that avoids breaking a site (eg. a PHP web site) when a user acceses the page while a file is still being uploaded (is incomplete).

Netbeans does somehting like: 

1. upload my-file.php.tmp
2. mv my-file.php.tmp my-file.php

Since the "mv" command is atomic, the site won't throw a syntax error while it's still being uploaded.

**Comment by Natizyskunk** [comment]
I don't really get it, a file upload take less than a second to be done so even if a user accesses a page while a file is still being uploaded, how could he get an error ? It should not even give one since the file should be uploaded as soon as it is saved.

I'm missig or missunderstanding something ?

**Comment by kripper** [comment]
Hi Natizyskunk,

Believe me, it happens and is very common.

When the user accesses the site while the file is being uploaded (1 or 2 second depending on the file size and bandwidth), the php engine will process an incomplete php page and throw syntax errors or missing functions.

If it's a production site with hundreds or thousands users, you will always cause errors and noise on customers without this feature.

That's the reason NetBeans implemented it.

**Comment by Natizyskunk** [comment]
Wait a minute, you're modifying files directly on a production server without using a versioning service like GIT ?... 😲

If I follow what you're saying, how are versioning service like GIT doing to not encounter this problem ?  Are thery also using a temporary file solution ?

For the atomic part of the `mv` command, that's what i can find about it : 
- `mv` is not always atomic.
- `mv` is only atomic for any individual file provided that the file is moved within the same filesystem.
- `mv` is most definitely not atomic when the move that it performs is from one filesystem to another, or when a remote filesystem cannot implement the mv operation locally.
- `mv` is at best atomic only per file.
- To move a group of files in a destination simultaneously, consider putting them in a directory and moving that directory. This single object (the directory) can be moved atomically.

So if you follow these points, the easiest way is to upload the whole folder that contain your modified file. This will move atomically the whole folder and this way you should not have any syntax error.

Maybe i'm wrong but for me you should never modify by hand a single file on a production server. You should always go throw the versioning service and then do a pull on your production server. Also if you want to try something without pushing it on production, maybe a pre-production server could be the solution.

Sorry but I'm quite new to this so I'm trying my best to make this extension working again.

It would be awesome if you could give me more infos about how it's done in NetBeans for example.

**Comment by kripper** [comment]
Yes, that's right, but sometimes you just need to make a little change on a single file on production. For example, when you change a config.php file.

Since mv is atomic per file, it's fine to use it.

Note that NetBeans does this by default and if you want to disable this feature you have to check the option "Upload file Directly (temporary file is not used). File transfer is faster but less safe, so use with caution".

Therefore, NetBeans considers it unsafe to upload files directly as vscode-sftp is doing at the moment.

This are NetBeans logs:

STOR config.php.new
File receive OK.
RNFR config.php.new
RNTO config.php
Rename successful.

To implement this feature, you will basically only need to change the destination file name adding a .new extension and then execute an additional command to move the temp file to its final destination.

**Comment by Natizyskunk** [comment]
Ok I see, I'm gonna look at it and try my best to implement this feature.

**Comment by kripper** [comment]
Hi Natizyskunk, did you get to take a look at it?

**Comment by Natizyskunk** [comment]
Yes but i haven't been able to find an easy way to implement it. I'm still struggling with understanding how the extension is coded and which dependecies it relies on for specific functions to work.

**Comment by kripper** [comment]
Ok, I'm going to help you. Just give me a quick intro please.
I forked and cloned your repo, and copied the folder inside the .vscode\extensions folder.
After restarting Visual Code, the extension is visible as "installed" but the extension commands were not loaded.
How did you setup your environment?

**Comment by kripper** [comment]
Ok. I'm going to send a pull request.

**Comment by kripper** [comment]
See https://github.com/Natizyskunk/vscode-sftp/pull/29

**Comment by rightdroid** [comment]
> Yes but i haven't been able to find an easy way to implement it. I'm still struggling with understanding how the extension is coded and which dependecies it relies on for specific functions to work.
> 
> Maybe you could help, pull requests are more than welcome ^^

Just wanted to say thanks for picking this extension up. I had a go at it myself (with the aim of introducing more functionalities), but it took more brain twisting than I had time and energy for.

**Comment by kripper** [comment]
I created a [pull request for fixing the bug](https://github.com/Natizyskunk/vscode-sftp/pull/41) and [another pull request to enable upload atomicity](https://github.com/mscdex/ssh2/issues/1054) (only supported for openSSH servers).

**Comment by Natizyskunk** [comment]
@kripper,
Everything has been merged, thx a lot m8 !!
