### ISSUE TITLE
Missing File Icons on SFTP:Explorer in VSCode version 1.68

### ISSUE THREAD

**Issue by Drsmed** [Natizyskunk/vscode-sftp#168]
**Describe the bug**
The file icons on remote explorer disappear on version 1.68

**To Reproduce**
Best descibed on liximomo/vscode-sftp
https://github.com/liximomo/vscode-sftp/issues/998

Desktop (please complete the following information):
OS: Mac and Windows
VSCode Version 1.68

**Comment by nebrot** [comment]
See also for a possible fix https://github.com/microsoft/vscode/issues/151663#issuecomment-1151766801. I think this file needs to be fixed: https://github.com/Natizyskunk/vscode-sftp/blob/db6f938679fc39e397a3d05ea99be2caef824431/src/modules/remoteExplorer/treeDataProvider.ts#L102-L126

**Comment by Drsmed** [comment]
VsCode 1.68.1 roled out today and after update icons work again.

**Comment by nebrot** [comment]
Thanks for info, it's working for me too after update to 1.68.1.

**Comment by Natizyskunk** [comment]
Just update to latest version of vscode and extenion.
