### ISSUE TITLE
File run after/before upload

### ISSUE THREAD

**Issue by jarodium** [Natizyskunk/vscode-sftp#169]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to be able to run some commands before or after upload. For example, I would like to, just before the upload, run sourceguardian ( php code encrypter ) and then, upload the resulting file to the server. This would allow me a step, since I run sourceguardian from the command line to encrypt the files and then I have to upload the files manually. It was best for me if SFTP add a development folder and a production folder, where the product of the command that ran would land before running the actual command. In the end of the command call, SFTP would upload that file into the server ( also would be awesome to have dual configurations, one for the dev server and one for the production ).

**Describe alternatives you've considered**
I have considered creating a file watcher to monitor the file changes, but since I lack the skills to build extensions, I would not be sure if the watcher would ran before SFTP starts the upload.

**Does this project help you?**
- [x] Yes. Especially the ability to use it in theia-ide. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@jarodium,

you can easily achieve this with the vscode built-in Tasks.

The easiest way is to open your project with vscode, go inside the root folder and type CTRL+SHIFT+P, type `Tasks:` and select the option `Tasks: Configure Task`. Now select `create tasks.json file from template` and `Others Example to run an arbitrary external command` This will create a tasks.json file inside a .vscode folder at the root of your project.

Now open this file and simply add those lines : 
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run sftp.sync.localToRemote",
            "command": "${command:sftp.sync.localToRemote}",
        },
        {
            "label": "Run Sourceguardian encrypter before sftp.sync.localToRemote",
            "type": "shell",
            "command": "soucreguardian.exe",
            "args": ["-v"],
            "dependsOrder": "sequence",
            "dependsOn": ["Run sftp.sync.localToRemote"]
        },
    ]
}
```
**⚠ Dont forget to change the `command` with the sourceguardian executable/script and `args` with your possible arguments (this is optional).**

Now go again inside the root folder and type CTRL+SHIFT+P, type `Tasks:` and this time select the option `Tasks: Run Task`.
You can now use your task by typing CTRL+SHIFT+P and running the command `Tasks: Run Sourceguardian encrypter before sftp.sync.localToRemote`.

Now everytrime you call this command, your sourceguardian ecrypter will be executed just before sftp synchronize `local to remote`.

To explain you a little bit more, you can find official vscode documentation about tasks [here](https://code.visualstudio.com/docs/editor/tasks#vscode).

Hope this helped you 😃

**Comment by dsent** [comment]
@Natizyskunk Hi! I'm trying to implement something similar. Is there a way to access a vscode-sftp config variable from a task? What I'm trying to do is something like this:
`"command": "ssh -t ${sftp.currentProfile.username}@${sftp.currentProfile.host} -p ${sftp.currentProfile.port}"`
