### ISSUE TITLE
FTPS still not work

### ISSUE THREAD

**Issue by phamminhkhac** [Natizyskunk/vscode-sftp#17]
i try
`{
    "name": "My Server",
    "host": "my.domain.com",
    "protocol": "ftp",
    "port": 990,
    "secureOptions": {
        "rejectUnauthorized": false
    },
    "secure": true,
    "username": "myusername",
    "password": "123123",
    "remotePath": "/",
    "uploadOnSave": true
}`
I also try secure = false and rejectUnauthorized = true but not work

Still connect normally via winscp but could not connect from this plugin also liximomo

**Comment by isaumya** [comment]
I'm pretty sure this is for ssh2 v1.1.0 as well, what do you think @Natizyskunk ?

**Comment by Natizyskunk** [comment]
@phamminhkhac,

This error has been maybe introduce with the ssh2 package update to v1.1.0.

As a test to verify that you can try this : 
1. Uninstall SFTP extension from vscode.
2. Close vscode and go to `C:/Users/<username>/.vscode/extensions`. 
3. In here remove all references to the SFTP extension. Liximomo's one and Natizyskunk's one.
4. Re-open vscode and install latest liximomo's version, not mine.
5. Re-close vscode and navigate now to `C:/Users/<username>/.vscode/extensions/liximomo.sftp-1.12.9`.
6. In here edit the package.json file to update the ssh2 package version from 0.8.5 to 1.1.0 like this
![image](https://user-images.githubusercontent.com/59120131/125477738-c2400bf0-176b-42a7-87ec-7b48c9648f73.png)
!! Don't forget to save !!
7. Now open a terrminal inside the extension folder `C:/Users/<username>/.vscode/extensions/liximomo.sftp-1.12.9` and type `npm i` to update all the packages.
9. After that you can open vscode again and try to connect via the SFTP extension.
10. Now check if you still have the error or not. This will confirm if the bug is coming from the new ssh2 update.

Please give me your feedback.

**Comment by phamminhkhac** [comment]
If I don't modify the version to 1.1.0 and then `npm i`, no error appears
but I got error like this if `npm i' with version 1.1.0

ssh2@1.1.0 install C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2
node install.js

C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v12.18.2 rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v12.18.2 rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  binding.cc
  win_delay_load_hook.cc
C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28
): error C2131: expression did not evaluate to a constant [C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\n
ode_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28
): message : failure was caused by a read of a variable outside its lifetime [C:\Users\Anynomous\.vscode\extensions\lix
imomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\build\sshcrypto.vcxproj]
C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto\src\binding.cc(1718,28
): message : see usage of 'this' [C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\prot
ocol\crypto\build\sshcrypto.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe" failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v12.18.2" "rebuild"
gyp ERR! cwd C:\Users\Anynomous\.vscode\extensions\liximomo.sftp-1.12.9\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to build optional crypto binding

trying to install ssh2 1.1.0 mannually and come back soon

**Comment by Natizyskunk** [comment]
I see, this error is not something that stop the extension from working, it's just telling you that it's missing some crypto-bindings but as they are optional this is not a problem.
If you really want to fix this you can follow these instructions : 
1. Install Visual C++ Build Environment: Visual Studio Build Tools (using "Visual C++ build tools" workload).
2. Install Python 2.7 (v3.x.x is not supported).
3. Then in powershell as admin type `npm config set python python2.7`.
4. Then type `npm config set msvs_version 2017`.
5. Install Cmake and add it to your PATH.
6. Exit and restart PC.
7. Open a terminal in the extension folder and retry to do an `npm i ssh2@^1.1.0`.
7. Voilà it should work now without errors but as I already said, this change nothing.

**Comment by Natizyskunk** [comment]
When done so please give me some feedback and tell me if you still encoutered the bug you open this issue for.

**Comment by phamminhkhac** [comment]
It works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Natizyskunk** [comment]
I'm glad to hear that 😀
