### ISSUE TITLE
Repeatedly asked for password even though set in SFTP config

### ISSUE THREAD

**Issue by zigojacko** [Natizyskunk/vscode-sftp#170]
On one of our projects, I am asked for the password when I go to View > Command Palette > SFTP: List even though it already exists in the config.

I can't see any errors with the syntax and plenty of other projects with same config is connecting fine.

I am wondering whether it might be because of this character in the password (^) - does this need to be escaped?

When I do enter the password again, it does connect fine - but it's just a hassle it asks when it is already defined.

**Comment by ain-soph** [comment]
Similar issue #135

**Comment by Natizyskunk** [comment]
@zigojacko @ain-soph,
Please keep track of this bug on this issue as it's the same and has been open before. This is just to eliminate duplicates 🙂
