### ISSUE TITLE
The installed extension is not displayed in the menu bar

### ISSUE THREAD

**Issue by GeniustudioDima** [Natizyskunk/vscode-sftp#175]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.

**Is your feature request related to a problem? Please describe.**
The installed extension is not displayed in the menu bar 
https://prnt.sc/kgDolU0kY-Ts

**Comment by Asitis** [comment]
This is happening for me too, now.
Thing is, I always had a Ubuntu laptop running VSCode with this extension - no problem. I replaced it last month with a new Ubuntu laptop running VSCode with this extension, still no problem!
That laptop broke and was very bad all over, so I got a M1 MacBook - and now the module doesn't show up..
