### ISSUE TITLE
Upload Active File doesn't see that I renamed my folder

### ISSUE THREAD

**Issue by tahola** [Natizyskunk/vscode-sftp#176]
Hello, I have an issue that I never had before, I changed the name of a directory from "domains" to "Domains" and now when I am using the "Upload Active File" **shortcut** it still uploading the file to "domains/myfile.php", if I do a right click on the file and > "Upload" the path is correct.  

I tried to relaunch the app, I also reinstalled the extension but nothing change, is there a cache somewhere that I could delete ?

Thank you for your time

**Comment by tahola** [comment]
Ok after trying to rename, delete, rename again etc.. I found the solution : I had to modify something in the file to have an update in my git directory, then I did "Upload changed files" and now "Upload active file" is working with the correct folder name (Domains).

**Comment by LeninZapata** [comment]
I have the same problem, I rename a folder "app" to "App", but it only happens when creating the "app" folder, I made many changes, but nothing makes the files upload correctly, it always creates the folder with a lowercase "app".

**Comment by tahola** [comment]
Yes I confirm that the bug still here.
