### ISSUE TITLE
SFTP does not work for AWS Linux 2022

### ISSUE THREAD

**Issue by jmcpheters** [Natizyskunk/vscode-sftp#188]
**Do you read the FAQ?**
- [X ] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
vscode-sftp v1.15.14 does not work for AWS Linux 2022 (AL2022), which is available as Release Candidate and supposedly soon to be Generally Available. Using key-pairs that work for AWS Linux 1 (AL1), no ssh connection can be established for AL2022 for an sftp transfer. Note that all my ssh clients (putty, cygwin/Openssh) would fail to connect to AL2022 until I updated every one. I cannot find a more current vscode-sftp version, so update does not look like an option, hence I am opening this ticket. The error when attempting to upload a file is: All configured authentication methods failed

Version information is:
# AL2022 - AWS Linux version where vscode-sftp does NOT work:
      __|  __|_  )
       _|  (     /   Amazon Linux 2022 AMI
      ___|\___|___|  Preview
http://aws.amazon.com/linux/amazon-linux-2022
[ec2-user@ip-10-16-129-0 ~]$ ssh -V
OpenSSH_8.7p1, OpenSSL 3.0.3 3 May 2022
----------------------------------------------------------------
# AL1 - AWS Linux version where vscode-sftp works as expected:
       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|
https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/
[ec2-user@ip-172-16-129-0 ~]$ ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

AWS tech support (which confirmed the problem in their lab) says that since other clients worked after update, then vscode-sftp must need some kind of update. I could not find in the change logs for working clients what update must have been done for compatibility, other than updating their OpenSSH versions. For vscode-sftp, I see in the change log an update to support OpenSSH_8.8, but that change must not have fixed the incompatibility that currently exists with AL2022.

**To Reproduce**
Issue appears to be 100% reproducible and as of this date the most recent AL2022 AMI is ami-0f5d32d3c2d85503c. Our AL2022 instances have been updated to that version, and the sftp problem remains. For reproduction, I recommend using the t2.micro EC2 instance type since it is in the free tier.

Once the instance is launched, confirm ssh using a client that is known to work with AL2022 (most current version of putty or OpenSSH on Cygwin will do). BTW: my cygwin OpenSSH version is:
$ ssh -V
OpenSSH_8.9p1, OpenSSL 1.1.1q  5 Jul 2022

Once ssh is confirmed, try to upload a file using vscode-sftp.  If configured correctly (host, username, etc) the transfer to an AL2022 instance will not work, but rather result in "All configured authentication methods failed".

**Expected behavior**
Successfully upload/download of files using vscode-sftp is the expected behavior.

**Screenshots**
I've attached a file (auth_fail.jpg) that shows the error message in the lower left corner. Note that clicking on the Detail button provided no other information.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Prod, Version 10.0.19044
 - VSCode Version 1.71.0 (see vscode_version.jpg showing output from Help>About)
 - Extension Version 1.15.14

**Extension Logs from Startup** - *required*
I have attached the following files:
- sftp-al2022.txt : shows debug log excerpt for failing connection to the AL2022 instance.
- sfpt-al1.txt : shows debug log excerpt for successful connection (and sftp transfer) to an AL1 instance (works for AL2 BTW).
- audit_vscode.txt : AL2022 audit.log excerpt for ssh connection failure from vscode-sfpt
- audit_cygwin.txt : AL2022 audit.log excerpt for ssh connection success from cygwin/OpenSSH

![auth_fail](https://user-images.githubusercontent.com/11933681/188936262-69e83496-959e-42e2-8385-de046a3b340f.jpg)
![vscode_version](https://user-images.githubusercontent.com/11933681/188937458-c515ee56-4a68-41bc-8127-49ae95e96952.jpg)
[sftp-al2022.txt](https://github.com/Natizyskunk/vscode-sftp/files/9508261/sftp-al2022.txt)
[sftp-al1.txt](https://github.com/Natizyskunk/vscode-sftp/files/9508268/sftp-al1.txt)
[audit_vscode.txt](https://github.com/Natizyskunk/vscode-sftp/files/9508276/audit_vscode.txt)
[audit_cygwin.txt](https://github.com/Natizyskunk/vscode-sftp/files/9508285/audit_cygwin.txt)

**Comment by Natizyskunk** [comment]
@jmcpheters,

You can try one of those options to see if it help : 
- [SSH agent](https://github.com/Natizyskunk/vscode-sftp/wiki/SFTP-only-Config#agent)
- [OpenSsh - Enable atomic file uploads](https://github.com/Natizyskunk/vscode-sftp/wiki/Common-Config#openssh)
- [Overriding the default transport layer algorithms](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#error-connection-closed)
- [Ssh config path](https://github.com/Natizyskunk/vscode-sftp/wiki/SFTP-only-Config#sshconfigpath)

I'm sorry to not be able to help you more since i've never worked with aws and i can't actually find any help on the web for this problem.

I'll keep you updated if any fix is found.

**Comment by Natizyskunk** [comment]
@jmcpheters Can you upload to the latest sftp extension version and retry it please ? I've made some several changes.

**Comment by jmcpheters** [comment]
Sadly the latest release makes no difference. The debug output has the same
messages, etc. I ran all the same tests to verify it works for AL1, and it
still does not work for AL2022 (but does work with some other clients).

**Comment by Natizyskunk** [comment]
@jmcpheters,
Sorry to hear that 😕 I'll keep an eye on this issue and let you know whenever it's fixed.?

**Comment by jamesastound** [comment]
Tried to replicate with `amzn2-ami-kernel-5.10-hvm-2.0.20220912.1-x86_64-gp2` and `amzn2-ami-kernel-5.10-hvm-2.0.20220912.1-arm64-gp2` and `amzn2-ami-hvm-2.0.20220912.1-x86_64-gp2`
@Natizyskunk/SFTP v1.15.19
VSCode Version: 1.72.2 (Universal/MacOS)

Config:
```
{
  "name": "My Server",
  "host": "<IP address>",
  "protocol": "sftp",
  "port": 22,
  "username": "ec2-user",
  "privateKeyPath": "./<key>pem",
  "remotePath": "/home/ec2-user",
  "uploadOnSave": false,
  "useTempFile": false,
  "openSsh": false
}
```

All worked as expected.

Tried mix of x86/arm64 and diff kernel versions.

```
[10-16 07:22:07] [info] config at /Users/james/Downloads/test {"remotePath":"/home/ec2-user","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"My Server","host":"***.***.***.***","port":22,"username":"******","privateKeyPath":"<key>.pem"}
[10-16 07:22:29] [info] local ➞ remote /Users/james/Downloads/test/.vscode/sftp.json
[10-16 07:22:36] [info] local ➞ remote /Users/james/Downloads/test/test.txt
[10-16 07:25:13] [info] remote ➞ local /Users/james/Downloads/test/test.txt
[10-16 07:25:20] [info] local ➞ remote /Users/james/Downloads/test/test.txt
[10-16 07:26:42] [info] remote ➞ local /Users/james/Downloads/test/test.txt
[10-16 07:26:55] [info] folder transfered.
[10-16 07:26:55] [info] folder transfered.
[10-16 07:26:55] [info] folder transfered.
[10-16 07:26:55] [info] remote ➞ local /Users/james/Downloads/test/.bash_logout
[10-16 07:26:55] [info] remote ➞ local /Users/james/Downloads/test/.bash_profile
[10-16 07:26:55] [info] remote ➞ local /Users/james/Downloads/test/.bashrc
[10-16 07:26:55] [info] remote ➞ local /Users/james/Downloads/test/test.txt
[10-16 07:26:56] [info] remote ➞ local /Users/james/Downloads/test/.ssh/authorized_keys
[10-16 07:26:56] [info] remote ➞ local /Users/james/Downloads/test/.vscode/sftp.json
```

I usually use Ubuntu, not AWS-Linux, but with newer versions of ubuntu, my old `pem` key stopped working, due to disabling of RSA depreciation. Not sure how close AWS-Linux is to Ubuntu, but possibly try creating a new Key Pair and trying again. That was the solution, with Ubuntu.

**Comment by jamesastound** [comment]
Might be related to #198

**Comment by jmcpheters** [comment]
One of the first things I tried when troubleshooting was to use a new key pair, but I generated it using the AWS default of RSA. 

I tried a new ED25519 key pair and I can connect no problem.

Problem resolved. Yeah!
