### ISSUE TITLE
Can't config ftp with no username

### ISSUE THREAD

**Issue by gogito** [Natizyskunk/vscode-sftp#194]
Basically if I try to set the username to null -> "", it doesn't work. And the server I need to connect to doesn't have a username and password so I need to set it to "". Is there any solution?

Thanks in advance!

**Comment by Natizyskunk** [comment]
How can your server not have any username ? An os can't have no user or a user with no username.
What i recommend you is to connect to your server via ftp in your terminal the classic way and look at hte user you're logged in.

It should look something like this : `root@myserver:/var/www/`. 
```
username = root
hostname = myserver
folder path = /var/www/
```
