### ISSUE TITLE
Include only specific files

### ISSUE THREAD

**Issue by U5B** [Natizyskunk/vscode-sftp#202]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
I saw the feature "ignore" which ignores specific files that match that pattern.
However, is it possible to make a feature that acts as the opposite of that?
I want to include only configuration files that end with `.yml`. But I don't want to go through and exclude every other filetype.

Similar to this https://github.com/Natizyskunk/vscode-sftp/issues/128
but for including specific filetypes

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@U5B,
You can easily achieve this by using the [watcher option](https://github.com/Natizyskunk/vscode-sftp/wiki/Common-Configuration#watcher) in your `sftp.json` config file.

Exemple : 
```json
"watcher": {
    "files": "*.yml",
    "autoUpload": false,
    "autoDelete": false
},
```

**Comment by U5B** [comment]
> @U5B, You can easily achieve this by using the [watcher option](https://github.com/Natizyskunk/vscode-sftp/wiki/Common-Configuration#watcher) in your `sftp.json` config file.
> 
> Exemple :
> 
> ```json
> "watcher": {
>     "files": "*.yml",
>     "autoUpload": false,
>     "autoDelete": false
> },
> ```

Unfortunately, that doesn't work for files ending in `.yml` in subfolders.

**Comment by Natizyskunk** [comment]
@U5B,
Could you try to use this `**/*.yml` instead of `*.yml` in the `files` option please ?

**Comment by U5B** [comment]
Unfortunately that downloads all files, not just files with the ending of `.yml`

**Comment by Natizyskunk** [comment]
@U5B,
Last try like this `"files": "**/*.{yml}",`. Not sure if `*/*.{yml}` also work or not.

**Comment by jayyren** [comment]
is there an option to exclude files from watching?

**Comment by Natizyskunk** [comment]
@jayyren,
Just add it to your 'ignore' list.
