### ISSUE TITLE
sftp.json file

### ISSUE THREAD

**Issue by andreherful** [Natizyskunk/vscode-sftp#214]
Hello,

I have installed sftp extension on vs code.
if I follow the instruction to change the sftp.json file on my side when I click cmd+shift+p there is no file name inside that folder.

where do I find that file?

thank you for your help,
André

**Comment by arvislacis** [comment]
@andreherful There are at least two possible solutions:

1. Just create file manually under `.vscode/sftp.json` in your project folder;
2. When doing Ctrl/Cmd+Shilf+P then type in/search for command `SFTP: Config`, clicking on it should create mentioned file also.
