### ISSUE TITLE
Unable to save or upload file

### ISSUE THREAD

**Issue by liuxiangxin** [Natizyskunk/vscode-sftp#22]
**Do you read the FAQ?**
- [ √] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

development environment
![image](https://user-images.githubusercontent.com/87697785/126300652-a753fa5f-b527-4b6e-a633-6e420a7d1c24.png)

sftp.json
![image](https://user-images.githubusercontent.com/87697785/126301138-2d24f3eb-4a52-4fb7-a978-10edf20a06b1.png)

sftp debug
![image](https://user-images.githubusercontent.com/87697785/126300229-67e7e0bd-669e-43de-8f7a-3cdd7a8888a4.png)

**Comment by liuxiangxin** [comment]
After auto saving, it turns around all the time. After testing, other FTP programs can connect to the server normally

**Comment by Natizyskunk** [comment]
Firstly I know it sound a littlbe bit stupid but check that your sftp.json config file is correctly configured, then verify that you only have one instance of the SFTP extension installed? Only mine and not also liximomo's one. Do do that just take à look inside `C:\Users\<username>\.vscode\extensions`.

Also please try adding those lines to your sftp.json config file : 

```json
{
  "secure": true,
  "ignore": [".vscode", ".git", "node_modules", ".DS_Store", "cache"],
  "concurency": 1,
  "connectTimeout": 1800000,
  "remoteTimeOffsetInHours": 0,
  "keepalive": 40000
}
```

Notes :
- For the `secure` option, set it to `true` for both control and data connection encryption, `'control'` for control connection encryption only, or `'implicit'` for implicitly encrypted control connection (this mode is deprecated in modern times, but usually uses port 990) . Default is `false`
- Don't forget that when connecting via FTP your `remotePath` root is the folder you're placed in when logging in with your ftp user. Ex: if connected as Natizyskunk, default root folder for Natizyskunk will be `/usr/Natizyskunk/` so if i want to connect to `/usr/Natizyskunk/www` i'll have to only specify `/www`.

Also don't forget that SFTP extension is only connecting with passive mode and is not capable of active mode, at least for now as I'll add this option in the near future.

If you still encounter some problems please refer to the [Error: Failure section](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#error-failure) in the FAQ.
