### ISSUE TITLE
Problem with files which name contains umlauts

### ISSUE THREAD

**Issue by Shirobaka** [Natizyskunk/vscode-sftp#23]
**Do you read the FAQ?**
- [X] Yes.
- [x] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
While downloading a project, this extension seems to have problems handling files which contains umlauts in their filename, for these files i get "File or directory not found".

**To Reproduce**
1. Create a File on remote side which filename contains umlauts like ä, ö, ü, ß.
2. try to download from remote in visual code.

**Expected behavior**
Files with filenames contains umlauts should be downloaded (and uploaded), like every other file too.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version 1.58.2
 - Extension Version 1.13.6

**Extension Logs from Startup** - *required*
[log.txt](https://github.com/Natizyskunk/vscode-sftp/files/6899497/log.txt)

**Comment by Natizyskunk** [comment]
The problem come from the UNICODE format as it's not always correctly recognized.

To fix it just rename your file without any accent or special character.

Also just as a reminder, here are some basic development rules for your filenames :
- Avoind using accents as they are considered special characters (UNICODE bug).
- Don’t start or end with a space, period, hyphen, or underline.
- Keep your filenames to a reasonable length and be sure they are under 31 characters.
- Most operating systems are case sensitive; always use lowercase.
- Avoid using spaces and underscores; use a hyphen instead. This will also improve your search engine rankings.
