### ISSUE TITLE
integrate .pem file for login

### ISSUE THREAD

**Issue by Yusuke1998** [Natizyskunk/vscode-sftp#234]
Is it possible to implement login with file_access.pem in sftp protocol?

**Comment by Natizyskunk** [comment]
@Yusuke1998,
Please respect the [feature_request template](https://github.com/Natizyskunk/vscode-sftp/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md) and give more details 🙂

**Comment by sanaazmeh** [comment]
That would be great!
