### ISSUE TITLE
Lower / uppercase bug (from liximomo days)

### ISSUE THREAD

**Issue by mooseh** [Natizyskunk/vscode-sftp#24]
**Is this a similar or duplicate feature request?**
- [x] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
Say we have myscript.py and we rename it locally to Myscript.py
then we rename it externally as Myscript.py when you next save the file it will show as Myscript.py locally
but will save as myscript.py externally, completely ignoring casings.

**Describe the solution you'd like**
For it to recognise the case has been changed and save remotely with uppercase

**Describe alternatives you've considered**
literally everything, you have to close VSCode, edit the filename remotely then re pull the files with the correct casings for it to work.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

** Additional Comments **
I just wan't to say a massive thankyou for picking up this liximomo sftp plugin, please get yourself a donate / grab me a coffee link, I would happily donate as long as the plugin works as intended :) thanks again

**Comment by Natizyskunk** [comment]
@mooseh,
I understand your problem but you can easily just rename your file(s)/folder(s) locally, remove it/them externally and then upload them again from local.

For your index fie exemple :
1. Remove file on remote.
2. Rename file on local.
3. Save and upload file from local to remote.

I'm still gonna take a look at it and see what i can do.

**Comment by Natizyskunk** [comment]
Related issue : #110

**Comment by Natizyskunk** [comment]
@mooseh,
A specific `fix-case-rename` version that work with Windows will be added to the Release section but it'll not be added directly to the v1.16.2 untill I'm sure it also work with Mac and Linux.

**Comment by Natizyskunk** [comment]
@mooseh,
I've published a new `pre-v1.16.2` pre-release that should fix your problem. You can download it [here](https://github.com/Natizyskunk/vscode-sftp/releases/tag/pre-v1.16.2) or directly from VSCode.
![image](https://user-images.githubusercontent.com/59120131/204685005-69a0b836-cf8f-4187-ae7a-295c5ceddc72.png)
![image](https://user-images.githubusercontent.com/59120131/204685143-2c3be7cb-ecd4-450d-9bc2-90afc982b1ee.png)
