### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by ProtocolLive** [Natizyskunk/vscode-sftp#240]
When i rename a file modifying only the first letther to upper case, the extension keep sending the file with lower case...

![image](https://user-images.githubusercontent.com/39626142/198386509-587881ac-4c7f-4818-b775-0580abbebfcd.png)
![image](https://user-images.githubusercontent.com/39626142/198386467-30bdb487-59f8-4895-9a25-a6d020c8c435.png)

Extension: v1.15.20

**Comment by NyaPPuu** [comment]
duplicate: #24 #86 #110

**Comment by antivanity** [comment]
Would love to use SFTP, however this bug stops me from using it. When is 1.16.2 coming out?

**Comment by Natizyskunk** [comment]
@ProtocolLive, @antivanity,
A specific `fix-case-rename` version that work with Windows will be added to the Release section but it'll not be added directly to the v1.16.2 unless I'm sure that it work with mac and linux.

**Comment by Natizyskunk** [comment]
@antivanity, @ProtocolLive,
I've published a new `pre-v1.16.2` pre-release that should fix your problem. You can download it [here](https://github.com/Natizyskunk/vscode-sftp/releases/tag/pre-v1.16.2) or directly from VSCode.
![image](https://user-images.githubusercontent.com/59120131/204685005-69a0b836-cf8f-4187-ae7a-295c5ceddc72.png)
![image](https://user-images.githubusercontent.com/59120131/204685143-2c3be7cb-ecd4-450d-9bc2-90afc982b1ee.png)
