### ISSUE TITLE
File synchronization

### ISSUE THREAD

**Issue by lecomteb27** [Natizyskunk/vscode-sftp#25]
**Do you read the FAQ?**
- [X] Yes.
- [X] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I don't really understand, if I delete a file or a folder on my PC,
will this deletion also be impacted on my remote space (Ionos hosting)?

**To Reproduce**
1. Go to 'VScode'
2. Run command 'Supprimer un fichier ou un dossier de son espace de travail'
3. See error

**Expected behavior**
Delete a file or a folder, it automatically deletes it on the remote space.

**Screenshots**
No screenshots available at this time

**Desktop (please complete the following information):**
 - OS: Windows => 10
 - VSCode Version => 1.58.2
 - Extension Version => 1.13.6

Thanks ;)

**Comment by Natizyskunk** [comment]
@lecomteb27,
If you're unsing the default configuration then no you'll never have files or folders deleted on your server when you delete them on your PC.

If you want to have this option to be active, you've to specify it in your `sftp.json` config file via the `watcher` parameter like so : 
```json
"watcher": {
    "files": "**/*",
    "autoUpload": true,
    "autoDelete": true
},
"uploadOnSave": false
```
For the `files` option  you can use `"**/{css/style.css,js/script.js}"` to watch changes made only to those specifics files.
For the `autoUpload` option, setting it to `true` will upload file(s) on every save operation of VSCode and/or when file(s) changed.
For the `autoDelete` option, setting it to `true` will delete file(s) on every operation of VSCode and/or when file(s) is removed.

Now when you delete a file or a folder on your PC it should also be deleted on your server.

**!! IMPORTANT !!**
If you watch everything like so `**/*`, Don't forget to set `uploadOnSave` to `false`.
If you don't watch everything you can set it to true or remove it.

Also please, be carefull with this configuration as you'll not be able to retrieve you're file(s)/folder(s) if you deleted them on your PC without doing it on purpose. In this case, making backups is the best way.
