### ISSUE TITLE
Add Feature - Upload on Changed

### ISSUE THREAD

**Issue by tlcd96** [Natizyskunk/vscode-sftp#265]
**Is this a similar or duplicate feature request?**
- [x] I don't know. I will go check it.
- [ ] No.

**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
when a file is changed, check a setting like `uploadOnChange` to see if sftp should upload the changed file (not the save files)

**Describe alternatives you've considered**
there's none

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@tlcd96,
You should already be able to do that using the `watcher.autoUpload` parameter inside your sftp.json config file.
You can find [here](https://github.com/Natizyskunk/vscode-sftp/wiki/Configuration#watcherautoupload) how to do it.
