### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by ericzhao007** [Natizyskunk/vscode-sftp#27]
**Screenshots**
![image](https://user-images.githubusercontent.com/21306882/128796088-37c77f7d-9669-4ed3-ac33-c653a8e6552e.png)

**Desktop :**
 - OS: Mac
 - VSCode Version [e.g. 1.59.0]
 - Extension Version [e.g. 1.14.0]

**Comment by fabrazer** [comment]
Maybe just try a lager timeout as mentioned here #20 

`"connectTimeout": 1800000`

**Comment by ericzhao007** [comment]
The same configuration can work under liximomo/vscode-sftp.

**Comment by ericzhao007** [comment]
`[08-13 15:49:04] [error] Error: [xxx]: Timed out while waiting for handshake
	at Client.<anonymous> (/Users/xxx/.vscode/extensions/natizyskunk.sftp-1.14.0/dist/extension.js:61:100690)
	at Client.emit (events.js:327:22)
	at Timeout._onTimeout (/Users/xxx/.vscode/extensions/natizyskunk.sftp-1.14.0/node_modules/ssh2/lib/client.js:995:16)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7) download `

**Comment by ericzhao007** [comment]
this is my config:
{
    "name": "My Server",
    "host": "localhost",
    "protocol": "sftp",
    "port": 22,
    "username": "xxxx",
    "privateKeyPath": "~/.ssh/xxx_158",
    "remotePath": "/webroot/phpsrc/xxx",
    "password": "xxx",
    "passphrase": "xxx",
    "uploadOnSave": true,
    "ignore": [".vscode", ".git", ".DS_Store"],
    "profiles" : {
       "baike_158" : {
            "host": "xxxx"
        },
    },
    "defaultProfile" : "baike_158"
}

**Comment by ericzhao007** [comment]
I solved the problem with the following configuration.

**Comment by ericzhao007** [comment]
"algorithms": {
        "kex": [
            "ecdh-sha2-nistp256",
            "ecdh-sha2-nistp384",
            "ecdh-sha2-nistp521",
            "diffie-hellman-group14-sha1"
        ],
        "cipher": [
            "aes128-ctr",
            "aes192-ctr",
            "aes256-ctr",
            "aes128-gcm",
            "aes128-gcm@openssh.com",
            "aes256-gcm",
            "aes256-gcm@openssh.com"
        ],
        "serverHostKey": [
            "ssh-rsa",
            "ecdsa-sha2-nistp256",
            "ecdsa-sha2-nistp384",
            "ecdsa-sha2-nistp521"
        ],
        "hmac": [
            "hmac-sha2-256",
            "hmac-sha2-512",
            "hmac-sha1"
        ]
    }

**Comment by ericzhao007** [comment]
This may be an old question [https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-778684682](url)
