### ISSUE TITLE
Error al sincronizar enlace simbolico

### ISSUE THREAD

**Issue by Razielthc** [Natizyskunk/vscode-sftp#273]
[11-30 04:25:54] [error] Error: ENOENT: no such file or directory, open 'c:\Users\MIS Soporte\Documents\sipsa.tk\public\storage' when remote ➞ local c:\Users\MIS Soporte\Documents\sipsa.tk\public\storage

Recibo el siguiente error al sincronizar los archivos desde mi servidor al parecer el error se da al querer descargar un enlace simbólico

Servidor AlmaLinux
Cliente Windows 10

los archivos que intento descargar es un proyecto de laravel 9
![error sftp](https://user-images.githubusercontent.com/106299415/204774326-5bbe06d3-0efa-4feb-9087-07837b082aef.PNG)

**Comment by Natizyskunk** [comment]
@Razielthc Please respect the `Bug report` issue termplate available [here](https://github.com/Natizyskunk/vscode-sftp/issues/new/choose) when opening a new issue. Also please write in english.
