### ISSUE TITLE
The old SFTP worked great,  this doesnt, why ?

### ISSUE THREAD

**Issue by thebrandon** [Natizyskunk/vscode-sftp#279]
its not privatekeypath its privatekey
then its unsupported format.  of what?  fuckitty fuck fuck i have lost
4 days fucking around with this horseshit

my question is

WHAT THE FUCK?!?!?!

**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

**To Reproduce**
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.51.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by whittede** [comment]
What is the unintended behavior here? I'm having trouble parsing.

**Comment by thebrandon** [comment]
This was the last thing down there, but seems like a good intro...
You emailed me so I guess the ticket was somewhat effective, I am sorry and hope I can help get this working so
others dont have to have this issue.
------------------
The SFTP extension for VSCode worked perfectly.  No issues whatsoever.

That was removed and I was forced to change to the Natizyskunk SFTP extension.  Since the change I think on 12/8 or 12/9 I have not been able to save code changes and have those changes be SFTP'd to my server as they have been.

From what I recall I had an error with my ppk file that worked just fine.  So I thought I found something that said that it wasnt PrivateKeyPath it was just PrivateKey so I changed that

Then, the file is in an unrecognized format
The fix for this is to not use the PUTTY ppk file
So I have to convert the file to something else.   But like why?  It just worked last week?
Anyway, Microsofts instructions to convert the file leave out pretty important details like where to put the files, on my dev computer or on AWS.  does it matter how i convert the file or what I use, should it be on ubuntu or windows?

Im kinda smart, but I just cant understand how to follow the instructions for anything UNIX or anything really.
But in the end I usually figure it out.

Its just this time I had issues transferring my domain from godaddy to wtf ever
and then issues implementing SQLite that came down to the rights to a file, but it doesnt say that anywhere, and when SQLite has a Fatal Error it deletes the database.   Like who/what does that?  delete the entire database... does a DROP DB or some shit and  if you dont know that, its an interesting one to figure out.

So I was kind of on a roll with the SQLite then I was roadblocked by this and with all of it I put in that ticket...
Which actually had some resources to troubleshoot in the problem entry form that I hadn't seen anwhere else.

But I still did the ticket, I'm sorry, it was uncalled for.  Hope at least it entertained a little because most often I just have to sit here and laugh at the 60 tabs I have open and how I have gone around in the same circle 10 times... what else can you do.
------------------
You emailed me so I guess the ticket was somewhat effective, I am sorry and hope I can help get this working so others dont have to have this issue.
(and Im moving this to the beginning of the email)

Thanks,
Brandon

________________________________

**Comment by whittede** [comment]
> The SFTP extension for VSCode worked perfectly.  No issues whatsoever. That was removed and I was forced to change to the Natizyskunk SFTP extension.

I'm not familiar with "_the SFTP extension for VSCode_". I've only worked with the Natizyskunk's extension, so I apologise for my unfamiliarity with this other extension you mention.

> Its just this time I had issues transferring my domain from godaddy to wtf ever and then issues implementing SQLite that came down to the rights to a file, but it doesnt say that anywhere, and when SQLite has a Fatal Error it deletes the database.   Like who/what does that?  delete the entire database... does a DROP DB or some shit and  if you dont know that, its an interesting one to figure out.

I'm sorry, that sucks to hear.

> But I still did the ticket, I'm sorry, it was uncalled for.  Hope at least it entertained a little because most often I just have to sit here and laugh at the 60 tabs I have open and how I have gone around in the same circle 10 times... what else can you do.

Understandable, everyone gets a little ragey sometimes. So this GitHub issue is ready to be closed?

**Comment by thebrandon** [comment]
No this github is not ready to be closed.

Ok so I need to be more specific.
The SFTP extension subtitled SFTP/FTP sync by liximomo for VSCode worked perfectly. No issues whatsoever with the SFTP extension subtitled SFTP/FTP sync by liximomo for VSCode . The SFTP extension subtitled SFTP/FTP sync by liximomo for VSCode  was removed and I was forced to change to the SFTP extension subtitled SFTP/FTP sync by Natizyskunk for VSCode and havent been able to save a file to or get a file from my server using the SFTP extension subtitled SFTP/FTP sync by Natizyskunk for VSCode.

[12-19 05:33:41] [error] Error: [ec2-54-148-187-131.us-west-2.compute.amazonaws.com]: All configured authentication methods failed
    at Client.<anonymous> (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\dist\extension.js:2:279830)
    at Client.emit (node:events:538:35)
    at Client.emit (node:domain:475:12)
    at doNextAuth (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\client.js:805:14)
    at tryNextAuth (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\client.js:993:7)
    at USERAUTH_FAILURE (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\client.js:373:11)
    at 51 (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\protocol\handlers.misc.js:337:16)
    at Protocol.onPayload (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherNative.decrypt (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\protocol\crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (c:\Users\brandon\.vscode\extensions\natizyskunk.sftp-1.16.1\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) download c:\Brandon\Development\temp.php




________________________________

**Comment by khimera80** [comment]
Hi!

I had the same exception stacktrace, although I just installed and used the extension for the first time ever.

In the debug output, I noticed that applied auth method was `password`, while the server only allows `publickey,keyboard-interactive`. Though `keyboard-interactive` is also just password entry when logging in on the linux console, it is a different method internally. 

I then added the following to the sftp config/profile: 
```
         "interactiveAuth" : [ "mypasswordstring" ]
```

and now it works. Maybe this helps with your problem, as well.

**Comment by flipkickmedia** [comment]
Ok so PPK is not a standard, its PuTTY specific.  Export your PPK to something standard, like a PEM encoded key.

In terms of config, this is mine taken from a working setup which uses password protected ssh keys:
```
    {
      "name": "cme-platform-api staging service defs",
      "host": "ninja.flipkick.media",
      "protocol": "sftp",
      "port": 22,
      "username": "root",
      "remotePath": "/etc/systemd/system",
      "uploadOnSave": true,
      "downloadOnOpen": true,
      "useTempFile": true,
      "openSsh": true,
      "privateKeyPath": "/home/tshaw/.ssh/id_rsa",
      "passphrase": true,
      "syncOption": {
        "update": true,
        "delete": true
      },
      "watcher": {
        "files": "*.{service}",
        "autoUpload": true,
        "autoDelete": true
      }
    },
```
