### ISSUE TITLE
Exclude remote folders

### ISSUE THREAD

**Issue by TheGreyRaven** [Natizyskunk/vscode-sftp#287]
Is there a way to exlude certains folders from downloading?
I have this config:
```
{
    "name": "name",
    "host": "ip",
    "protocol": "sftp",
    "port": 22,
    "username": "username",
    "remotePath": "/",
    "uploadOnSave": false,
    "useTempFile": false,
    "openSsh": false,
    "remoteExplorer": {
        "filesExclude": [
            "cache",
            "logs"
        ]
    }
}
```
But the folders gets downloaded anyway, is it not possible to exclude remote folders?

**Comment by josecoelhomelo** [comment]
I think you're excluding from the remote explorer view only. For sync use the `ignore` param like so:

```
"ignore": [
        "this-is-a-folder",
        "this-is-a-file.js"
]```

**Comment by Natizyskunk** [comment]
@TheGreyRaven, 
Please use the "ignore" parameter as suggested by @josecoelhomelo.
