### ISSUE TITLE
THANK YOU for the resumption of the project vscode-sftp

### ISSUE THREAD

**Issue by vincent1890** [Natizyskunk/vscode-sftp#30]
Hello

Thank you for the resumption of the project which for more than two years is dormant and is no longer maintained by its original creator unfortunately, despite a huge potential and need of it.
I hope that you will take up the torch for a long time and continue and maintain this super extension.

Nothing that your update v1.14.0 is awesome and time expected and requested since time to liximomo but nothing had been done it is really great thanks to you.

sorry for the passage of this message by "Issue: Feature request" but I didn’t know what other means of communication to pass by to tell you.

Bye

**Comment by Natizyskunk** [comment]
Thx, it means a lot to me. I'm trying my best to maintain this extension even if i'm not really a vscode extension developer ^^
I'll take the time i can to look at the issues and fix everything I can.
Also feel free to help by making pull requests on new branches 😉
