### ISSUE TITLE
Upload active file (external to project) to selected folder

### ISSUE THREAD

**Issue by rightdroid** [Natizyskunk/vscode-sftp#31]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
Cannot upload a file that is not necessarily in your project folder to remote project. Ideally would work by using right click menu on a folder in Remote Explorer view. In Notepad++ you can have a file open (resides in temp folder), right click a remote folder from NppFTP plugin _Tree view_ and select to upload it to that folder. 

**Describe the solution you'd like**
With Notepad++ NppFTP plugin. You could right click a remote browser folder, select "Upload current file here" and it would upload it to remote server. The active file could be something outside of your current project. Use case: You have project B's `.htaccess` file open, and you want to upload it to some folder in project A, which is currently open in your remote explorer view. You right click the target folder and from context menu select "Upload active file".

**Describe alternatives you've considered**
Copying it your your local Project A folder and then uploading. This is and extra step in the workflow that Notepad++ can bypass.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

I once tried to implement it myself, albeit unsuccessfully. Seems like a feature we could do given the functionalities the extension has available.

**Comment by Natizyskunk** [comment]
@rightdroid ,
This is not how the SFTP extension is intended to work.

Can you give me a good example and reason to implement this feature ?
If it's really usefull, I'll keep an eye on it and try to add it in a future update.
