### ISSUE TITLE
changing the case of a filename does not get reflected on remote server

### ISSUE THREAD

**Issue by rayr007** [Natizyskunk/vscode-sftp#325]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Create a file named myawesomefile.php and it uploads to the server. Rename the file to myAwesomeFile.php and it still uploads to server as myawesomefile.php. Restarting VSCode and the bad name still persists. Delete the remote files and it still uploads with the wrong case.

**To Reproduce**
1. Create a file and let SFTP upload it to the server.
2. Rename the file in VSCode (change the case).
3. SFTP still uploads with wrong case.

**Expected behavior**
I expect the file to be uploaded with the correct case. Other changes to filename (change to myAwesomeFile2.php works so seems to be a caching issue).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux] Mac
 - VSCode Version [e.g. 1.51.0] 1.76.0
 - Extension Version [e.g. 1.7.0] 1.16.1

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by Natizyskunk** [comment]
Please try the new [pre-v.1.16.2](https://github.com/Natizyskunk/vscode-sftp/releases/tag/pre-v1.16.2) pre-release. It should implement the fix for this issue.

**Comment by shijunti19** [comment]
@Natizyskunk 根本没有解决
This problem has not been resolved yet
