### ISSUE TITLE
The command `SFTP: Download project` only copies directories and not files.

### ISSUE THREAD

**Issue by Zudjo** [Natizyskunk/vscode-sftp#346]
**Do you read the FAQ?**
- [ X ] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
The command `SFTP: Download project` only copies directories and not files.

**To Reproduce**
1. Create SFTP config file
2. Connect to the server successfully
3. Run command `SFTP: Download project`

**Expected behavior**
All project files and directories are copied locally exactly as in the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/113335680/236203793-0a4a8e37-8324-4e55-b6a8-1e717028f334.png)

**Desktop (please complete the following information):**
 - **OS:** Windows 11
 - **VSCode Version:** 1.77.3
 - **Extension Version:** 1.16.1

**Extension Logs from Startup** - *required*
See screenshot.

**Comment by Saturn745** [comment]
I had the same issue and managed to fix it by making the plugin ignore the "node_modules" folder.

**Comment by satiromarra** [comment]
@Zudjo The first step is to generate the complete folder structure and finally download the files.
Is it possible that you looked when I was in the first step? If there are many files, it can take a long time to generate the list.
