### ISSUE TITLE
Plugin not working after changing our azure FTP config to FTPS

### ISSUE THREAD

**Issue by ankeorum** [Natizyskunk/vscode-sftp#352]
My ftp host is an azure service deployment slot with ftps and implicit connection working on port 990. My current setup for sftp.json is:

{
    "name": "Azure Claimpro",
    "host": "myawesomehost.azure.net",
    "protocol": "ftp",
    "port": 990,
    "username": "mypreferredusername",
    "password": "ultraSecr3tPwd!",
    "remotePath": "/site",
    "uploadOnSave": true,
    "downloadOnOpen": true,
    "ignore": [
        ".vscode", 
        ".git", 
        ".DS_Store",
        "_notes",
        ".idea",
        "z_logs",
        "system_files"
    ]
}

Is there any property to let me connecting to my site? I have tried changing the protocol from ftp to ftps but ftps is not a valid value, the sftp plugin for sublime, which I presume is pretty similar works with the settings below but some of them do not apply for the vscode plugin, any ideas or advices?

Sublime Text sftp plugin settings:

{    
    // sftp, ftp or ftps
    "type": "ftps",

    "save_before_upload": true,
    "upload_on_save": true,
    "sync_down_on_open": false,
    "sync_skip_deletes": false,
    "sync_same_age": true,
    "confirm_downloads": false,
    "confirm_sync": true,
    "confirm_overwrite_newer": false,
    
    "host": "myawesomehost.azure.net",
    "user": "mypreferredusername",
    "password": "ultraSecr3tPwd!",
    "port": "990",
    
    "remote_path": "/site",
    "ignore_regexes": [
        "\\.sublime-(project|workspace)", "sftp-config(-alt\\d?)?\\.json",
        "sftp-settings\\.json", "/venv/", "\\.svn/", "\\.hg/", "\\.git/",
        "\\.bzr", "_darcs", "CVS", "\\.DS_Store", "Thumbs\\.db", "desktop\\.ini"
    ],

    "connect_timeout": 30,
    "ftp_passive_mode": true,
 
}

Please, help me as I love vscode but am not able to use it as long as we changed from ftp to ftps, thank you

[https://imgur.com/a/yUgsl6u](https://github.com/karikera/ftp-kr/issues/url) Here you have my configurations for PHPStorm and Dreamweaver which both works, I would need to replicate the same config on VSCode ftp plugin, any idea?

**Comment by ankeorum** [comment]
Any idea on this @Natizyskunk ? something I may be missing? I wonder if there is something to do with the secureOptions but I have no idea, tbh

**Comment by Natizyskunk** [comment]
@ankeorum can you try [this]](https://github.com/Natizyskunk/vscode-sftp/wiki/FTP(s)-only-Configuration#secure) please ?

**Comment by Natizyskunk** [comment]
@ankeorum This issue will be closed in 10 days if there is no more discussion.
