### ISSUE TITLE
Blacklist folders from auto upload on save

### ISSUE THREAD

**Issue by joel-gennari** [Natizyskunk/vscode-sftp#354]
**Is your feature request related to a problem? Please describe.**
When I save files I don't want uploaded to my server, they currently upload due to sftp.

**Describe the solution you'd like**
I would like to be able to indicate which folder or file I wanted ignored by the sftp extension.
eg. Right click folder or file/ SFTP - Ignore - TRUE

**Describe alternatives you've considered**
I've considered removing the folder entirely from the project, but don't want to run two projects when it could be solved by doing the above

**Does this project help you?**
Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@joel-gennari,

You should already be able to do that by adding the `ignore` parameter inside your sftp.json config file.
