### ISSUE TITLE
Error: No such file

### ISSUE THREAD

**Issue by devpremium** [Natizyskunk/vscode-sftp#36]
**Describe the bug**
Sometimes this error happens and the notification appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/52453013/130524415-623960b5-e279-4cc4-801d-884114303ecf.png)

**Desktop (please complete the following information):**
win 11, vscode last

**Comment by hendrikbursian** [comment]
Hey, I'm facing the same issue. I'm using WSL on Windows 10.

```
[08-24 00:50:55] [error] Error: No such file
	at 101 (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:2471:19)
	at SFTP.push (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:271:11)
	at CHANNEL_DATA (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/client.js:505:23)
	at 94 (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/handlers.misc.js:841:16)
	at Protocol.onPayload (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/Protocol.js:1974:10)
	at AESGCMDecipherNative.decrypt (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/crypto.js:992:26)
	at Protocol.parsePacket [as _parse] (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/Protocol.js:1943:25)
	at Protocol.parse (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/Protocol.js:281:16)
	at Socket.<anonymous> (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/client.js:692:21)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote /home/hendrik/workspace/**masked**
```

VSCode About
```
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
```

I remember that error from [liximomos version](https://github.com/liximomo/vscode-sftp) and switched to see it fixed.

The workaround for liximomos version was to replace the following condition in the `ssh2-streams` library in the `node_modules` folder of the extension:

`errorCode === STATUS_CODE.OK` with `errorCode === STATUS_CODE.OK || errorCode === STATUS_CODE.NO_SUCH_FILE`

I tracked it down to this place in Natizyskunks version: 

`$HOME/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:2467`. After replacing and reloading it worked for me.

Would be great tho if the extension would work without tweaking some of the internal libraries! Let me know if u need more info.

Thanks and props to @Natizyskunk for continuing the maintainance for this extension!

**Comment by Natizyskunk** [comment]
@hendrikbursian, 

Sorry to see this but as you just said, this error come from the external ssh2 dependency and i can't do much on my side since i'm not the creator of it. I'll try to get in touch with his developer to find a way to fix this.

In the meantime if you find any fix, feel free to create a pull request on a new branch.

**Comment by fanshengshuai** [comment]
> Hey, I'm facing the same issue. I'm using WSL 2 on Windows 10.
> 
> ```
> [08-24 00:50:55] [error] Error: No such file
> 	at 101 (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:2471:19)
> 	at SFTP.push (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:271:11)
> 	at CHANNEL_DATA (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/client.js:505:23)
> 	at 94 (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/handlers.misc.js:841:16)
> 	at Protocol.onPayload (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/Protocol.js:1974:10)
> 	at AESGCMDecipherNative.decrypt (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/crypto.js:992:26)
> 	at Protocol.parsePacket [as _parse] (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/Protocol.js:1943:25)
> 	at Protocol.parse (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/Protocol.js:281:16)
> 	at Socket.<anonymous> (/home/hendrik/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/client.js:692:21)
> 	at Socket.emit (events.js:315:20)
> 	at addChunk (internal/streams/readable.js:309:12)
> 	at readableAddChunk (internal/streams/readable.js:284:9)
> 	at Socket.Readable.push (internal/streams/readable.js:223:10)
> 	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote /home/hendrik/workspace/**masked**
> ```
> 
> VSCode About
> 
> ```
> Version: 1.59.1 (user setup)
> Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
> Date: 2021-08-19T11:56:46.957Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Windows_NT x64 10.0.19042
> ```
> 
> I remember that error from [liximomos version](https://github.com/liximomo/vscode-sftp) and switched to see it fixed.
> I made sure I have only this version installed by checking the extensions folder - both locally and the WSL server instance.
> 
> The workaround for liximomos version was to replace the following condition in the `ssh2-streams` library in the `node_modules` folder of the extension:
> 
> `errorCode === STATUS_CODE.OK` with `errorCode === STATUS_CODE.OK || errorCode === STATUS_CODE.NO_SUCH_FILE`
> 
> I tracked it down to this place in Natizyskunks version:
> 
> `$HOME/.vscode-server/extensions/natizyskunk.sftp-1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:2467`.
> 
> After replacing and reloading it worked for me.
> 
> Would be great tho if the extension would work without tweaking some of the internal libraries! Let me know if u need more info.
> 
> Thanks and props to @Natizyskunk for continuing the maintainance for this extension!

works for me, thank u !

**Comment by jjnxpct** [comment]
Yes this works for me to. Thanks!

**Comment by BBvT** [comment]
Worked for me too ;-)

**Comment by ahmetbarut** [comment]
It works. Thanks :smile: @hendrikbursian

**Comment by FM-O** [comment]
@hendrikbursian 
Your fix works indeed but still, the error should not occure anyway. You're walking around the error catch.

I don't think there's any problem with ssh2 dependency since it works fine with 1.14.0 version. Error raised from the package does not mean it comes from it.

**Moving back to 1.14.0** is a best option if you do not need the **useTempFile** feature.

**Comment by hatifnatt** [comment]
Issue is caused by new option [useTempFile](https://github.com/Natizyskunk/vscode-sftp/wiki/Common-Config#usetempfile) which is by default is set to `true`.  To fix issue with latest (1.15.1 - 2021-08-24) version of the extension you can add
`"useTempFile": false` to your sftp configuration.

**Comment by bmackenty** [comment]
> Issue is caused by new option [useTempFile](https://github.com/Natizyskunk/vscode-sftp/wiki/Common-Config#usetempfile) which is by default is set to `true`. To fix issue with latest (1.15.1 - 2021-08-24) version of the extension you can add
> `"useTempFile": false` to your sftp configuration.

I confirm this fix works.

**Comment by Natizyskunk** [comment]
Could you try new release and tell me if the bug has been fixed please ?

**Comment by hatifnatt** [comment]
It seems version 1.15.2 is working fine even with `"useTempFile": true`
@Natizyskunk thank you for the quick fix!

**Comment by Natizyskunk** [comment]
Happy to hear that ! No problem 😁
