### ISSUE TITLE
Watcher look on differents folders ?

### ISSUE THREAD

**Issue by MrC8** [Natizyskunk/vscode-sftp#386]
Is there a way to watch files in differents folders ?
I tried something like this : 
`"watcher": {
        "files": "wp-content/themes/mytheme/{folder_1,folder_2}/**/*.{js,css}",
        "autoUpload": true,
        "autoDelete": false
}`

**Comment by satiromarra** [comment]
@MrC8 Yes. 

```json
    "watcher": {
      "files": "wp-content/themes/mytheme/{folder_1,folder_2}/**/*.{js,css}",
      "autoUpload": false,
      "autoDelete": false
    }
```

That configuration is watching and upload when the files is modified:
```
"wp-content/themes/mytheme/folder_1/bak/file.css"
"wp-content/themes/mytheme/folder_1/bak/cache/file.js"
"wp-content/themes/mytheme/folder_2/bak/admin.css"
....
```
But not this:
```
"wp-content/themes/mytheme/folder_2/style.css"
```
