### ISSUE TITLE
The "fd" argument must be of type number. Recieved undefined - error after update 1.15.0 & 1.15.1

### ISSUE THREAD

**Issue by salievvm** [Natizyskunk/vscode-sftp#40]
**Do you read the FAQ?**
- [x] + Yes.
- [x] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
After syncing remote -> local i see an error. This error change the files, and my git recognize them as modified. I have centos server and i connect this from windows client.

**To Reproduce**
1. Update extension to 1.15.0
2. Choose sftp profile 
2. Run command sync Remote -> Local
3. See error

**Expected behavior**
No errors

**Screenshots**
https://drive.google.com/file/d/1AOKMYdhdF1Si_KfzAxTZzcv8OdpXJnTZ/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 10.0.19043
 - VSCode Version 1.59.0
 - Extension Version 1.15.0 - 1.15.1
https://drive.google.com/file/d/1BtTjpXNMSzgwlpYPM5F57f53W-rV1doA/view?usp=sharing

**Extension Logs from Startup** - *required*
https://drive.google.com/file/d/12sVfPYrIuDfW9_f8_w2rgDJq-_dgKQxz/view?usp=sharing

**Comment by jjnxpct** [comment]
I think this is a duplicate issue of #34

**Comment by Natizyskunk** [comment]
Could you try new release and tell me if the bug has been fixed please ?

**Comment by jjnxpct** [comment]
I have installed the new version and this issue seems to be fixed. Excellent!
I also don't have the error 'Error: No such file' anymore. #36 

Thanks @Natizyskunk ! Keep up the good work!

**Comment by Natizyskunk** [comment]
I'm happy to hear that ! 😁
