### ISSUE TITLE
Feat Req: Ignore Certificate Issues

### ISSUE THREAD

**Issue by gravitytechau** [Natizyskunk/vscode-sftp#416]
G'day, 

I apologise if this is elsewhere, but searching didn't find it.

I've been using this extension for long enough to come across hosts that have SSL Certs in various states, but that doesn't mean I can just not upload to them. 

As such, it would be great if there were config options to allow us to ignore SSL issues. (Usually I'm thwarted by host name mismatches and expired certificates. The one I'm facing right now, is a valid certificate reporting as an expired one. I can't find out why)

So as noted, it would be great to see some config.json options where we can tell the extension to ignore some/all SSL issues.

Thanks for your efforts in maintaining this code :) I appreciate it.

**Comment by godsdog** [comment]
This would be great! I always have to switch to FileZilla, when this happens :(

**Comment by godsdog** [comment]
Ok I think this is a solution right now:

`
"secureOptions": {
        "rejectUnauthorized": false
    }
`

**Comment by Natizyskunk** [comment]
@gravitytechau @godsdog, I confirm you the "secureOptions.rejectUnauthorized" option is the one you need. I'm gonna document it in the Wiki and FAQ in the next release.
