### ISSUE TITLE
Stock on spin loading

### ISSUE THREAD

**Issue by devnhickxon** [Natizyskunk/vscode-sftp#421]
**Do you read the FAQ?**
- [/] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

**To Reproduce**
1. Go to your project
2. Click any file
3. Right Click
4. Choose Upload File
5. Repeat Upload File 3x to 5x to see the error

**Expected behavior**

**Screenshots**
![image](https://github.com/Natizyskunk/vscode-sftp/assets/109337622/31b77076-d20d-459a-a0b9-763f28e59b5e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version 1.81.1
 - Extension Version 1.16.3
 - 
**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
  4. 
[debug.txt](https://github.com/Natizyskunk/vscode-sftp/files/12487023/debug.txt)

**Comment by aaroncrawford** [comment]
Just started experiencing this as well.  Appears the file transfers, but the indicator never stops spinning.

**Comment by Natizyskunk** [comment]
@devnhickxon You can try to downgrade to v1.16.1 and see if it fix your problem.
