### ISSUE TITLE
Urgent repair

### ISSUE THREAD

**Issue by shijunti19** [Natizyskunk/vscode-sftp#429]
You only fixed the case issue by saving and uploading

The upload in the right click has not been fixed

你只修复了保存上传功能
右键里单机文件的上传没有修复，现在改成小写的依然无法正确上传

 https://github.com/Natizyskunk/vscode-sftp/pull/249

**Comment by shijunti19** [comment]
我晕，只能自己修复了

**Comment by Natizyskunk** [comment]
Please update your extension and retry. It should work.

**Comment by Natizyskunk** [comment]
Related issues #24, #86, #110, #240, #270?
