### ISSUE TITLE
Multiple remotePath

### ISSUE THREAD

**Issue by fisico95** [Natizyskunk/vscode-sftp#435]
How is possible to configure multiple remotePath on the same server?

For example, on the server XXX i need to access only to
remotePath : /xxx/123/folder and remotePath: /xxx/456/folder

Is a solution to my problem exist?

**Comment by satiromarra** [comment]
@fisico95 Have you tried using a profile by remote directory?

**Comment by Natizyskunk** [comment]
I close this issue since there's no news. Feel free to comment so I can reopen it.
