### ISSUE TITLE
Multiple configurations did not work. 

### ISSUE THREAD

**Issue by TQLeung** [Natizyskunk/vscode-sftp#467]
I have the configuration code like below, It seem not work correctly, when I press F1 (SFTP:Sync Local -> Remote)，only show an option. I thought it shoud be show two option, but only one. Is there something wrong with my configuration?

![image](https://github.com/Natizyskunk/vscode-sftp/assets/66344500/59531c46-63ac-40a6-8519-a1a1bd01dcdd)

## sftp.json
```
[
    {
        "name": "RX_Pro_App",
        "host": "app1",
        "protocol": "sftp",
        "port": 22,
        "username": "root",
        "remotePath": "/root/wp/rx",
        "uploadOnSave": false,
        "useTempFile": false,
        "openSsh": false,
        "ignore": [
            ".vscode",
            ".git",
            ".DS_Store",
            "target/**"
        ]
    },
    {
        "name": "RX_Dev",
        "host": "dev",
        "protocol": "sftp",
        "port": 22,
        "username": "root",
        "remotePath": "/root/wp/rx-cloud-backend",
        "uploadOnSave": false,
        "useTempFile": false,
        "openSsh": false,
        "ignore": [
            ".vscode",
            ".git",
            ".DS_Store",
            "target/**"
        ]
    }
]
```

**Comment by krmu** [comment]
+1

**Comment by krmu** [comment]
> +1

Try to set context for those hosts. That worked for me.

**Comment by kleingeo** [comment]
Are contexts paths on meant for the host or local? It isn't clear what they represent.

**Comment by TQLeung** [comment]
> Are contexts paths on meant for the host or local? It isn't clear what they represent.

Contexts path serves local.

**Comment by TQLeung** [comment]
> > +1
> 
> Try to set context for those hosts. That worked for me.
Thanks to answer me。BUT IT IS NOT I NEED。
I need a solution that one FILE PATH upload to two different destinations（2 ip address）， and when I press F1，the tool bar shows two options for me。

**Comment by sickerin** [comment]
@TQLeung I think, the best you can do is to is to setup do multiple profiles. You can switch between the profiles using `SFTP: Set Profile`, to choose which server you might want to upload by default or on save. Unfortunately, you can't save to both servers, you would need to trigger it manually every time using these
![image](https://github.com/Natizyskunk/vscode-sftp/assets/12108084/abe70452-3090-44bc-a33d-fe0902670361)

```
{
  "profiles": {
    "dev": {
      "host": "dev-host",
      "remotePath": "/dev",
    },
    "prod": {
      "host": "prod-host",
      "remotePath": "/prod"
    }
  },
  "defaultProfile": "dev"
}
```
You can refer to this other issue
https://github.com/Natizyskunk/vscode-sftp/issues/187

**Comment by sjhsbhqf** [comment]
> @TQLeung I think, the best you can do is to is to setup do multiple profiles. You can switch between the profiles using `SFTP: Set Profile`, to choose which server you might want to upload by default or on save. Unfortunately, you can't save to both servers, you would need to trigger it manually every time using these ![image](https://private-user-images.githubusercontent.com/12108084/301035226-abe70452-3090-44bc-a33d-fe0902670361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjU3NTksIm5iZiI6MTcxMzk2NTQ1OSwicGF0aCI6Ii8xMjEwODA4NC8zMDEwMzUyMjYtYWJlNzA0NTItMzA5MC00NGJjLWEzM2QtZmUwOTAyNjcwMzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzMzA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOWIzYTkwNGI0ZmVlNjcwYzgyNWI3NDI5NWJjYWE2YTIyMGVlMmI3M2IzYWUxN2U4MGZiMGIxNmI5YmRkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.glEGIMzlZDUvk9dnGXVhKz8hH1je7LLxpaNDKIiGbQs)
> 
> ```
> {
>   "profiles": {
>     "dev": {
>       "host": "dev-host",
>       "remotePath": "/dev",
>     },
>     "prod": {
>       "host": "prod-host",
>       "remotePath": "/prod"
>     }
>   },
>   "defaultProfile": "dev"
> }
> ```
> 
> You can refer to this other issue #187

This instance configuration will prompt that there is no 'name'

**Comment by TQLeung** [comment]
> @TQLeung I think, the best you can do is to is to setup do multiple profiles. You can switch between the profiles using `SFTP: Set Profile`, to choose which server you might want to upload by default or on save. Unfortunately, you can't save to both servers, you would need to trigger it manually every time using these ![image](https://private-user-images.githubusercontent.com/12108084/301035226-abe70452-3090-44bc-a33d-fe0902670361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzMzNTIsIm5iZiI6MTcxNDAzMzA1MiwicGF0aCI6Ii8xMjEwODA4NC8zMDEwMzUyMjYtYWJlNzA0NTItMzA5MC00NGJjLWEzM2QtZmUwOTAyNjcwMzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA4MTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YmQ0ZTliMTE5ODgxZDMyMjNkMDIzMTUwNTRmMDk1NWFjMmYwYTllNzNhM2JhMTIxNjYwZTFlMWViZjc0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZBTrQw62du1tOdnTzKtTDU48Zo0iHl-1RHbaFT3NjRQ)
> 
> ```
> {
>   "profiles": {
>     "dev": {
>       "host": "dev-host",
>       "remotePath": "/dev",
>     },
>     "prod": {
>       "host": "prod-host",
>       "remotePath": "/prod"
>     }
>   },
>   "defaultProfile": "dev"
> }
> ```
> 
> You can refer to this other issue #187

It works! Brilliant man! Thank you very much!!
