### ISSUE TITLE
Refresh filelist after deleting a file / folder

### ISSUE THREAD

**Issue by jjnxpct** [Natizyskunk/vscode-sftp#47]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [X] No.

**Is your feature request related to a problem? Please describe.**
When I delete a file of folder I need to close the explorer view (click on the top level folder) then refresh the view and go back to check if the file / folders is indeed gone. If I don;t do this the file is still showing even though it is actually deleted from the server.

**Describe the solution you'd like**
It would be great to auto refresh the view after deleting a file or folder on the remote server so we can quickly see the deletion was successful.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
Can you be more precise ?
As i understand, when you have your local project open in vscode, you want to be able to delete a file or a folder on your remote server and be able to see thoses changes applied in your local project ? 
Exemple: Delete <remote-file> should delete <local-file> ?

If you want to see every delete from you local project to be applied on your remtoe server, you have to use the watcher option in your sftp.json config file like this : 
```json
"watcher": {
        "files": "**/*",
        "autoUpload": true,
        "autoDelete": true
    },
    "uploadOnSave": false, // set to false if watcher `autoUpload` is set to true & `files` is set to "**/*".
```
When a file will be remove from your local project, it'll also be deleted on your remote server.

Only thing you can't do is to delete a file on your remote server and see it deleted in your local project without refreshing the view explorer.

**Comment by BBvT** [comment]
I think the question is to have the sftp-explorer-view autorefresh. Without having to push the refresh-button in the sftp-explorer-view.

**Comment by jjnxpct** [comment]
Yes @BBvT that's what I meant.  Thanks. 

When we delete a file or folder in the remote explorer we need to refresh manually. Otherwise the deleted file is still visible there. I think the file listing is cached somehow. Also, when we have a subfolder open and delete some file refreshing the file listing only seems to work when we close all folders (select the root) and the refresh. When the deleted file or folder is 'in the view' refreshing using the refresh button does not seem to work OK.

Auto-refreshing the folder listing would be great. So when we delete a file it will be gone in the 'view'.

Hope this helps ;-)

**Comment by Natizyskunk** [comment]
#122, #134, #159
