### ISSUE TITLE
Chargement impossible

### ISSUE THREAD

**Issue by babache** [Natizyskunk/vscode-sftp#48]
Bonjour,

marre que liximomo qui marche une fois sur 2, je me suis tourné vers ton extension mais j'ai toujours des problèmes..

Impossible de charger le module et je ne sais pas pourquoi, comment je peux savoir pourquoi il ne se lance pas ?

Je fais un ctrl + p et ">SFTP: config", en bas apparait : "Activation des extentions" mais rien ne se lance.. 

Ça commence à me rendre dingue ce vscode !!!

Je suis sous WIN10, j'ai rien dans la console de développement.. je sais pas trop où regarder et relancer VSCode ou désactiver/réactiver l’extension rien n'y fait.

![image](https://user-images.githubusercontent.com/2962513/130739305-209409b5-ecfc-4c1e-9ff9-351d856c782f.png)

**Comment by Natizyskunk** [comment]
Bonjour @babache,

Dans un premier temps je te conseille d'ouvrir vscode, de faire un CTRL+x (ou d'aller dans l'onglet extensions) et de vérifier que tu as bien désinstaller toutes les instances de l'extension SFTP, que ce soit celle de liximomo, la mienne ou encore celle d'autres développeur.
Ensuite rends toi dans le dossier `C:\Utilisateurs\<nom_d'utilisateur>\.vscode\extensions` et ici pareil tu supprimes tous les dossiers faisant référence à l'extension SFTP, celle de liximomo ou la mienne.

Enfin je te conseil de vérifier que tu as bien la dernière version de vscode et que tu as les droits administrateur sur ta machine.

Maintenant il ne te reste plus qu'à installer ma dernière version 1.15.2 de SFTP directement dans l'onglet extension de vscode soit en suivant ce [lien](https://marketplace.visualstudio.com/items?itemName=Natizyskunk.sftp).
