### ISSUE TITLE
Publish on open-vsx.org

### ISSUE THREAD

**Issue by woifes** [Natizyskunk/vscode-sftp#49]
First I want to say a big THANK YOU for reviving the project.

I am considering to transit to vscodium instead of vscode. The only thing which is holding me back is this extension. So I wanted to ask if you plan on publishing this also on https://open-vsx.org/
I dont know if this is a big deal but here is a tutorial https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

vscodium article: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by Natizyskunk** [comment]
No problem 😉
