### ISSUE TITLE
Is "syncMode": "full", Needed and What's its Purpose?

### ISSUE THREAD

**Issue by black-eye** [Natizyskunk/vscode-sftp#53]
This is neither bug report nor feature request, just a question to verify. But firstly, let me thank you for forking the extension and taking care of it! It really saved my day!

Now for the question: when syncing from local to remote this setting is recommended (at least works for me fine):

```
"syncOption": {
    "update": true,
    "delete": true
},
"syncMode": "full",

```
Ref.: https://github.com/liximomo/vscode-sftp/issues/573

I'm just curious, wheather the `"syncMode": "full",` is needed and what's it's purpose. The parameter is not decribed in Wiki and it seems to me that it might be an obsolete parameter.

Thanks for the clarification, and keep up the good work.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
This option is not really used anymore because if you correctly configure the `watcher` and the `syncOption` you'll have the same behaviour but if you want you can still specify it.

For informations : 
> This option is only in relation to how Sync to remote or Sync to local works. 'update' means that it only affects files that exist in both remote and local. 'full' means not only existing files but also created files or deleted files will be synchronized.
> 
> The download is a copy operation. And I think it's clear how sync works that I explained in above question. I will give you a more detail example.
> 
> According to these two directories.
> 
> ```
> source-dir
>    |- s1.txt
> dest-dir
>     |-d1.txt
>     |-d2.txt
> ```
> 
> When you download `source-dir ` to `dest-dir` the `dest-dir` will be
> 
> ```
> dest-dir
>     |-d1.txt
>     |-d2.txt
>     |-s1.txt
> ```
> 
> Back to starting point. When you sync `source-dir ` to `dest-dir` with `syncMode: 'update'`. Nothing changes, because there are no files in common.
> 
> ```
> source-dir
>    |- s1.txt
> dest-dir
>     |-d1.txt
>     |-d2.txt
> ```
> 
> when you sync `source-dir ` to `dest-dir` with `syncMode: 'full'`.
> 
> ```
> source-dir
>    |- s1.txt
> dest-dir
>     |-s1.txt
> ```
> 
> The two directory will be exactly same.

You can find more info [here](https://github.com/liximomo/vscode-sftp/pull/58).
