### ISSUE TITLE
sftp.json settings are not loaded until retrying many times

### ISSUE THREAD

**Issue by kripper** [Natizyskunk/vscode-sftp#56]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When edditing and saving sftp.json file, the extension normally reloads the settings.
When we have many profiles in the sftp.json file, the new settings fail to load (no messages in output window), but it works fine after retrying many times (eg: after retrying 6 times when we have 5 profiles)

**To Reproduce**
1. Create many profiles
2. Open the extension output window to see if the settings are being reloaded or not.

**Expected behavior**
Should work the first time.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version: 1.59.1
 - Extension Version: 1.15.2

**Comment by Natizyskunk** [comment]
Hey man,

Is your issue still a thing ? 
If needed I'll take a look at it in the next  days.
