### ISSUE TITLE
Can I delete my server's file in VS Code?

### ISSUE THREAD

**Issue by arangpaul** [Natizyskunk/vscode-sftp#58]
**Do you read the FAQ?**
- [o] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I deleted my local file and click SFTP: Local to Remote but my server has that deleted file..

**To Reproduce**
1. Make 'index_backup.html'
2. Run command > SFTP: Sync Local to Remote
3. Checked my server has 'index_backup.html'
4. Delete 'index_backup.html' in local
5. Run command > SFTP: Sync Local to Remote
6. See bug...?

**Expected behavior**
I want to delete deleted file in my server without using FileZillar,

**Desktop (please complete the following information):**
 - OS: WIN10 ver H1N1
 - VSCode Version [v1.59.1]
 - Extension Version [v1.15.2]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.

**Comment by arangpaul** [comment]
thanks :D

**Comment by Natizyskunk** [comment]
@arangpaul,

no problem 😀
