### ISSUE TITLE
Update ssh2 to at least 1.2.0

### ISSUE THREAD

**Issue by Tomeamis** [Natizyskunk/vscode-sftp#59]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x ] No.

**Is your feature request related to a problem? Please describe.**
Connecting to some servers can take 30 seconds or more. More on the problem [here](https://github.com/mscdex/ssh2/issues/1031). It was fixed in ssh2 v1.2.0.

**Describe the solution you'd like**
Please update ssh2 to at least v1.2.0. I have done so manually in my vscode install and everything seems to be working fine.

**Describe alternatives you've considered**

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@Tomeamis,
Thx for the info. ssh2 depedency has been updated to v1.4.0.

**Comment by Tomeamis** [comment]
Everything seems to be working fine. Thank you.
