### ISSUE TITLE
Show remote hidden files

### ISSUE THREAD

**Issue by jnaklaas** [Natizyskunk/vscode-sftp#61]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
I can't see hidden files in the SFTP Explorer (for example .env files). Is there a way to enable this?

**Describe the solution you'd like**
See remote hidden files in the SFTP Explorer.

**Describe alternatives you've considered**
None.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by arvislacis** [comment]
@jnaklaas If you are using SFTP connection then it should already work, look at my screenshot - https://i.imgur.com/7TUialP.png

If you are using Explorer to browser FTP connection then it may be a different story.

**Comment by jnaklaas** [comment]
Seems to be fixed indeed!

**Comment by Natizyskunk** [comment]
Related issues : #121, #183

**Comment by Natizyskunk** [comment]
Just in case for those using `proftpd`, please edit this config file `/etc/proftpd.conf`.
Search for the `ListOptions` parameter and change it from `"-l"` to `"-la"`.
