### ISSUE TITLE
Run sftp.sync.remoteToLocal at startup

### ISSUE THREAD

**Issue by Mhitra** [Natizyskunk/vscode-sftp#63]
Hi,
I'm sorry for bothering you, mine is more a question than a request.
I'd like to autorun "sftp.sync.remoteToLocal" command every time I open my workspace.
There is a way to do it?
I have tried by tasks.json but I failed.
Thank you so much.

**Comment by Natizyskunk** [comment]
@Mhitra,

No problem :)

you can easily achieve this with the vscode built-in Tasks.

The easiest way is to open your project with vscode, go inside the root folder and type CTRL+SHIFT+P, type `Tasks:` and select the option `Tasks: Configure Task`. Now select `create tasks.json file from template` and `Others Example to run an arbitrary external command` This will create a tasks.json file inside a .vscode folder at the root of your project.

![image](https://user-images.githubusercontent.com/59120131/135701535-45b969e8-6311-4f96-b79f-e1883f181c8e.png)
![image](https://user-images.githubusercontent.com/59120131/135701537-229752cc-4acc-45ed-88b9-acfb98e0e748.png)

Now open this file and simply add those lines : 
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run sftp.sync.remoteToLocal at startup",
            "command": "${command:sftp.sync.remoteToLocal}",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "runOptions": {
                "runOn": "folderOpen"
            }
        }
    ]
}
```
Now go again inside the root folder and type CTRL+SHIFT+P, type `Tasks:` and this time select the option `Tasks: Run Task`. You should get a prompt asking if you want to allow tasks to run automatically in that folder. Select yes as this is what you want.
If you didn't get this prompt, you can enable automatic tasks yourself by typing CTRL+SHIFT+P and running the command `Tasks: Allow Automatic Tasks in Folder`.

Next time you open your project, you will see your task running automatically in a new terminal (you should be able to see the SFTP wheel spining).


To explain you a little bit more, here is a list of the most important properties:
```
- label: The label used in the user interface.
- command: The actual command to execute. We want to execute `sftp.sync.remoteToLocal`.
- presentation: This defines how the task output is handled in the terminal.
      - reveal: always - The Integrated Terminal panel is always brought to front. Used to see the command running on startup, so this what you want.
      - panel: new - Every execution of that task is using a new clean terminal.
- runOptions: Defines when and how a task is run. It has the property:
      - runOn: folderOpen - The task will be run when the containing folder is opened. This is what we want!
```

Hope this helped you 😃

**Comment by Mhitra** [comment]
Thank you so much!!! Really!

**Comment by Mhitra** [comment]
I have an error:
[error] Error: Config Not Found. (file:///${command:sftp.sync.remoteToLocal}) 
But it works, I'm ok with it! Thank you so much again!
Thank you also to take care about this extension!

**Comment by Natizyskunk** [comment]
Yup I'm aware of the error buty it's just a false positive.
I'll try to deactivate this message.

**Comment by Mhitra** [comment]
Thank you Thank you Thank you for this v1.15.4 version just for me.

**Comment by Natizyskunk** [comment]
No problem 😉
