### ISSUE TITLE
Default uploadOnSave and privateKeyPath

### ISSUE THREAD

**Issue by nickdekruijk** [Natizyskunk/vscode-sftp#72]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [x] No.

**Is your feature request related to a problem? Please describe.**
Each time I create a new SFTP: Config file uploadOnSave is enabled by default. This has caused some problems in the past because I forgot to change it. Would be nice to have it on false by default. Also since I use SFTP with SSH keys I always need to add `"privateKeyPath": "~/.ssh/id_rsa",` too, would be nice to have that added by default too if possible.  

**Describe the solution you'd like**
Change the default config file with `"uploadOnSave": false,` and add `"privateKeyPath": "~/.ssh/id_rsa",`.

**Describe alternatives you've considered**
Don't forget to change manually.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@nickdekruijk,
I'll change the default `uploadOnSave` option to `false` but I can't set a default value for the `privateKeyPath` option because not everyone is using it by default. Some people are still using the classic "username + password" method.
