### ISSUE TITLE
File name case

### ISSUE THREAD

**Issue by kevin8990** [Natizyskunk/vscode-sftp#86]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I have a file Abc.txt, save and upload is ok. but when I change the file name to abc.txt, I always pass Abc.txt when upload.

**Comment by Natizyskunk** [comment]
This is a known bug. You've to delete the file on your server and then reupload the file and everything should work as expected.
Sorry for this inconvenience.

**Comment by Natizyskunk** [comment]
Realted issues : #24 #110 #240.
Should be fixed in the next update (v1.16.2).

**Comment by Natizyskunk** [comment]
@kevin8990,
A specific `fix-case-rename` version that work with Windows will be added to the Release section but it'll not be added directly to the v1.16.2 untill I'm sure it also work with Mac and Linux.

**Comment by Natizyskunk** [comment]
@kevin8990,
I've published a new `pre-v1.16.2` pre-release that should fix your problem. You can download it [here](https://github.com/Natizyskunk/vscode-sftp/releases/tag/pre-v1.16.2) or directly from VSCode.
![image](https://user-images.githubusercontent.com/59120131/204685005-69a0b836-cf8f-4187-ae7a-295c5ceddc72.png)
![image](https://user-images.githubusercontent.com/59120131/204685143-2c3be7cb-ecd4-450d-9bc2-90afc982b1ee.png)
