### ISSUE TITLE
cannot upload with private key

### ISSUE THREAD

**Issue by dexamenos** [Natizyskunk/vscode-sftp#9]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Upload on save does (still) not work, error is: 
````
[error] Error: [<hostname>]: connect EBADF <ip>:<60000>
	at Client.<anonymous> (/Users/<removed>/.vscode/extensions/natizyskunk.sftp-1.13.2/dist/extension.js:61:99994)
````

**To Reproduce**
Hit save, observe error, see output tab

**Expected behavior**
Save and upload works w/o error

**Screenshots**
–

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - VSCode 1.57.1
 - Extension Version 1.13.2

**Extension Logs from Startup** - *required*
````
[07-07 20:23:37] [info] [file-save] /Users/<removed>/Sites/<link/to/my/file>.php
[07-07 20:23:37] [trace] handle upload file for /Users/<removed>/Sites/<link/to/my/file>.php
[07-07 20:23:37] [debug] Custom crypto binding not available
[07-07 20:23:37] [debug] Client: Trying <hostname> on port 60000 ...
[07-07 20:23:37] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
[07-07 20:23:37] [debug] Socket error: connect EBADF <ip>:60000
[07-07 20:23:37] [error] Error: [<hostname>]: connect EBADF <ip>:60000
	at Client.<anonymous> (/Users/<removed>/.vscode/extensions/natizyskunk.sftp-1.13.2/dist/extension.js:61:99994)
	at Client.emit (events.js:327:22)
	at Socket.<anonymous> (/Users/<removed>/.vscode/extensions/natizyskunk.sftp-1.13.2/node_modules/ssh2/lib/client.js:724:12)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21) download /Users/<removed>/Sites/<link/to/my/file>.php
[07-07 20:23:37] [debug] Socket closed
````

sftp.json
````
{
    "name": "<removed>",
    "host": "<removed>",
    "protocol": "sftp",
    "port": 60000,
    "username": "root",
    "remotePath": "/<removed>",
    "privateKeyPath": "/Users/<removed>/.ssh/id_ed25519",
    "uploadOnSave": true
}
````

**Notes:**

- I use sftp, custom port.
- I have not set a password.
- I use key file (id_ed25519.pub), key is valid and available.
- VS Code has "full disk access" in macOS settings.
- I can connect in Terminal successfully, it also worked flawlessly with liximomo an last VS Code Version.
- I'm puzzled.

**Comment by Natizyskunk** [comment]
it seems to be an error on your end. I can't reproduce it. Personnally uploading via a private key is working perfectly fine for me.

I've some questions for you :
- why is there <removed> and <link/to/my/file>.php in your filepath ? Have you modified it before opening your issue ?
- Same, why is there <removed> in most of your parameters ?
- Have you added your local PC ssh public key in your server "authorized_keys" file inside the .ssh folder ? If not please do so and vice-versa (server public key in local pc "authorized_key").

Before investigating further could you try those steps please : 
1) Add your local PC ssh public key inside your server "authorized_key" file.
2) On your local PC create inside your .ssh folder a "config" file and add this inside it :
```
PubkeyAcceptedKeyTypes=+ssh-dss

Host <server_name>
	HostName <server_host/server_ip>
	User <ssh_user>
	Port <ssh_port>
	IdentityFile <ssh_private_key_filepath>
```
Don't forget to change permission and ownership : `chmod 600 ~/.ssh/authorized_keys` & `chown -R <username>:<username> ~/.ssh`
3) On windows in your SFTP.json config file all slashes contained in the private key path should be replaced with double anti-slashes (this `C:/Users/<Username>/.ssh` become this `C:\\Users\\<Username>\\.ssh`).
4) Retry to connect and upload with private key, it should work now.

**Comment by dexamenos** [comment]
Hi, and merci for the swift reply.

As already stated, I'm left puzzled.

To your questions:

* Why do I have `<removed>` there? So: I just removed my real username, my real file name and my real hostnames from the public, so please consider everything in between `<`...`>` as "edited for privacy"
1. of course is my pub key inside the server's authorized list; as I have stated, the connection also works flawlessly (with the same server as well as the same key) via Terminal.app or Transmit.app
2. tried with config file, no change
3. I'm on a mac, so I consider the double slash path delimiter as irrelevant

----

Additional observations:

* I use a custom port (i.e. 60000 instead of 22), however, this does not seem the be the reason as I have tested also with port 22 today
* I repeat: it works with same servers (tried with hostname as well as IP) when ssh'ing with Terminal or when using SFTP with Transmit.app, but not with your VSCode extension
* Interesting: it works with a machine on my local host (running exakt same configuration on server (Debian Buster, latest apt packages installed) but not with a remote machine on the internet (to be clear and repeat myself: it works in Terminal.app)
* I have also tried to use password auth, still no success

Any ideas where to look?

**Comment by Natizyskunk** [comment]
After some researches, Sadly I haven't found anything about your problem as you're the only one who have it and i'm not able to reproduce it. 
To be clear, on my end I can connect to different servers via FTPS, SFTP or SSH on default port 21, 22 or custom port with username/password or with username/private_key.

The only thing i can think of is that maybe you're using some non-supported algorithm for your SSH key. I'm personally always using `RSA` but as i can see you're using `ED25519` and it should also work. Could you try with an `RSA` key and give me the result ? Also How big bit is your key ? I know that the standard (more used) size is 2048-bit, maybe you've created yours with 4096-bit ?

I'm really sorry that I can't help you any further? I'll try my best to keep an eye on your issue.

**Comment by dexamenos** [comment]
@Natizyskunk : you might now officially beat me. 🤪🥊

I have solved the issue and it actually turned out to be on my end. 
**Disabled Litte Snitch** and everything works like a charm. 👍

I will still have to look into the details, as the VSCode binary was set to "allow all connection".

Merci beaucoup for spending your time!

**Comment by Natizyskunk** [comment]
I'm glad that you find a solution. Can you give me more infos about Litte Snitch as I don't know this program?

**Comment by dexamenos** [comment]
Little Snitch is basically an outgoing firewall. It is used to block outgoing traffic. 

See here for more details https://obdev.at/products/littlesnitch/index.html

I would assume that it is quite popular among Mac Users. 

You can block specific hostnames, ports or IP addresses for every binary. Although my VSCode was set to "allow all traffic" I must have messed up some rules and set some to deny. Maybe also something changed in one of the last VSCode updates, as I have noticed, a couple of helper processes are now used (Little Snitch blocks on a per-process level).

**Comment by Natizyskunk** [comment]
Thanks for those informations, I'll take a look at it 🙂
