### ISSUE TITLE
Ability to have a local path

### ISSUE THREAD

**Issue by Wingee** [Natizyskunk/vscode-sftp#95]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [X] No.

**Is your feature request related to a problem? Please describe.**
Ability to map a local sub folder to be synced to the remote folder or multiple local to remote folder mappings

**Describe the solution you'd like**
An example of the config could be:

{
    "name": "My Server",
    "host": "localhost",
    "protocol": "sftp",
    "port": 22,
    "username": "username",
    "remotePath": "/var/www/website/myroot",
    "localPath": "web",
    "uploadOnSave": true
}

With the above config files from web would be synced to the myroot folder on the remote.

**Describe alternatives you've considered**

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by Natizyskunk** [comment]
@Wingee,

Please just follow [this section](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#how-do-i-upload-content-inside-a-folder-but-not-the-folder-itself) in the FAQ since it's already something available.

Thx 😉
