### ISSUE TITLE
Packet length exceeds the max length.

### ISSUE THREAD

**Issue by yuqihang** [Natizyskunk/vscode-sftp#96]
**Error**:
> Packet length 1214346853 exceeds max length of 262144

**My Environment**:
 - OS: Win10
 - VSCode Version: 1.62.2
 - Extension Version: v1.15.10

**Extension Logs**:
> [error] Error: Packet length 1214346853 exceeds max length of 262144
>     at doFatalSFTPError (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\SFTP.js:2476:15)
>     at SFTP.push (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\SFTP.js:220:18)
>     at CHANNEL_DATA (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\client.js:525:23)
>     at 94 (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
>     at Protocol.onPayload (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
>     at AESGCMDecipherNative.decrypt (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\crypto.js:987:26)
>     at Protocol.parsePacket [as _parse] (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
>     at Protocol.parse (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
>     at Channel.<anonymous> (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\client.js:713:21)
>     at Channel.emit (events.js:315:20)
>     at addChunk (internal/streams/readable.js:309:12)
>     at readableAddChunk (internal/streams/readable.js:284:9)
>     at Channel.Readable.push (internal/streams/readable.js:223:10)
>     at CHANNEL_DATA (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\client.js:525:23)
>     at 94 (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
>     at Protocol.onPayload (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
>     at GenericDecipherNative.decrypt (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\crypto.js:1269:26)
>     at Protocol.parsePacket [as _parse] (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
>     at Protocol.parse (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
>     at Socket.<anonymous> (c:\Users\abc\\.vscode\extensions\natizyskunk.sftp-1.15.10\node_modules\ssh2\lib\client.js:713:21)
>     at Socket.emit (events.js:315:20)
>     at addChunk (internal/streams/readable.js:309:12)
>     at readableAddChunk (internal/streams/readable.js:284:9)
>     at Socket.Readable.push (internal/streams/readable.js:223:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) 

Why did this error happen? Can anyone please help me fix it? Thanks a lot!

**Comment by yuqihang** [comment]
There was something wrong with my bash setup script, and I solved the problem by eliminating error info from that script. May this can help other people coming across the same problem.

**Comment by DaanVerbaan** [comment]
Hi, I seem to have the same problem. Can you help me solving this?

Additional info: I connect to a host using a jump host. I work on a Macbook Pro

<img width="459" alt="Screenshot 2023-10-06 at 15 57 46" src="https://github.com/Natizyskunk/vscode-sftp/assets/48680747/1f59e612-54b4-4a85-83fa-cd4936750cab">

**Comment by yuqihang** [comment]
> Hi, I seem to have the same problem. Can you help me solving this?
> 
> Additional info: I connect to a host using a jump host. I work on a Macbook Pro
> 
> <img alt="Screenshot 2023-10-06 at 15 57 46" width="459" src="https://user-images.githubusercontent.com/48680747/273230117-1f59e612-54b4-4a85-83fa-cd4936750cab.png">

You can check whether your shell config files such as bashrc/zshrc return error messages (stderr) when you log in. 
In my case, I used `module` command to load some module files automatically when login, but some of them loaded unsuccessfully and returned stderr, which caused the `Packet length error`.
This is only my opinion and you can have a try. Actually, I don't really know what happened, may this could help you~

**Comment by DaanVerbaan** [comment]
Hi, thanks for your fast reply and the hints. 

Regards,

⁣Daan Verbaan
Uisce Web Development

Tel +31 (0)85 303 1199
Mob +31 (0)6 26736666​
